services:
  nginx:
    image: nginx:alpine
    depends_on: [php]
    volumes:
      - ./nginx/wiki.conf:/etc/nginx/conf.d/default.conf:ro
      - /wikis/sites:/srv/wikis:rw   # 一次挂载大目录
    labels:
      - traefik.enable=true
      - traefik.http.routers.wikifarm.rule=HostRegexp(`^.+\.pub\.wiki$`)
      - traefik.http.routers.wikifarm.entrypoints=websecure
      - traefik.http.routers.wikifarm.service=wikifarm
      - traefik.http.routers.wikifarm.tls.certresolver=cloudflare
      - traefik.http.routers.wikifarm.tls.domains[0].main=*.pub.wiki
      - traefik.http.services.wikifarm.loadbalancer.server.port=80
      - traefik.http.routers.wikifarm.priority=1
    networks:
      - proxy
      - farm
  
  php:
    image: mediawiki:1.44-fpm
    volumes:
      - /wikis/sites:/srv/wikis:rw
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./php-conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    networks:
      - wikinet
      - farm

networks:
  proxy:
    name: proxy
    external: true
  wikinet:
    name: wikinet
    external: true
  farm:
  
