services:
  nginx:
    image: nginx:alpine
    depends_on: [php]
    volumes:
      - ${HOST_CONFIG_DIR}/nginx/wiki.conf:/etc/nginx/conf.d/default.conf:ro
      - ${HOST_WIKIS_DIR}/sites:/srv/wikis:rw   # 一次挂载大目录
    labels:
      - traefik.enable=true
      - traefik.http.routers.wikifarm.rule=HostRegexp(`^.+\.pub\.wiki$`)
      - traefik.http.routers.wikifarm.entrypoints=websecure
      - traefik.http.routers.wikifarm.service=wikifarm
      - traefik.http.routers.wikifarm.tls.certresolver=cloudflare
      - traefik.http.routers.wikifarm.tls.domains[0].main=*.pub.wiki
      - traefik.http.services.wikifarm.loadbalancer.server.port=80
      - traefik.http.routers.wikifarm.priority=1
    networks:
      - proxy
      - farm
  
  php:
    image: mediawiki:1.44-fpm
    container_name: mediawikifarm
    volumes:
      - ${HOST_WIKIS_DIR}/sites:/srv/wikis:rw
      - ${HOST_WIKIS_DIR}/oauth:/oauth:ro
      - ${HOST_CONFIG_DIR}/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ${HOST_CONFIG_DIR}/php-conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    networks:
      - wikinet
      - farm

  redis:
    image: redis:latest
    networks:
      - wikinet
    command: ["bash", "-c", "redis-server --requirepass $$REDIS_PASSWORD"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

networks:
  proxy:
    name: proxy
    external: true
  wikinet:
    name: wikinet
    external: true
  farm:
  
