// Auto-generated by pack-templates.ts — do not edit manually.
// Generated at: 2026-03-29T13:23:12.951Z

export const TEMPLATE_HASHES: Record<string, string> = {
  'backend': '8395695aabf7',
  'frontend': '38f6a436130e',
  'game-sdk': 'f9b648f36540',
  'game-ui': 'aa84c0e60f90',
  'copilot-skills': '1879bcfa70fd',
  'designer-skills': '1a4f59e6cbe7',
} as const;
