// Auto-generated by pack-templates.ts — do not edit manually.
// Generated at: 2026-03-29T15:50:49.593Z

export const TEMPLATE_HASHES: Record<string, string> = {
  'backend': '8e748397cb40',
  'frontend': '38f6a436130e',
  'game-sdk': 'f9b648f36540',
  'game-ui': 'abb042aa0396',
  'copilot-skills': '1879bcfa70fd',
  'designer-skills': 'b5d6dfa11dea',
} as const;
