// Auto-generated by pack-templates.ts — do not edit manually.
// Generated at: 2026-03-29T15:21:27.115Z

export const TEMPLATE_HASHES: Record<string, string> = {
  'backend': '26e78984e795',
  'frontend': '38f6a436130e',
  'game-sdk': 'f9b648f36540',
  'game-ui': 'abb042aa0396',
  'copilot-skills': '1879bcfa70fd',
  'designer-skills': '1a4f59e6cbe7',
} as const;
