/**
 * Build script: pack template directories into .tar.gz archives.
 *
 * Usage:  npx tsx scripts/pack-templates.ts
 *
 * 1. Packs template source dirs into .tar.gz archives
 * 2. Copies archives to apps/studio/static/templates/ for serving
 * 3. Generates apps/studio/src/lib/simple-mode/template-hashes.generated.ts
 *    with content hashes — used by SimpleModeBridge to cache-bust fetches
 */

import { createTar, type TarEntry } from '@pubwiki/flow-core';
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, copyFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { gzip } from 'node:zlib';
import { createHash } from 'node:crypto';
import { promisify } from 'node:util';

const gzipAsync = promisify(gzip);

const ROOT = join(import.meta.dirname!, '..');

/** Template sources: name → source directory (+ optional extra files from parent) */
const TEMPLATES: { name: string; srcDir: string; extraFiles?: string[] }[] = [
  { name: 'backend',  srcDir: join(ROOT, 'templates', 'backend') },
  { name: 'frontend', srcDir: join(ROOT, 'templates', 'frontend') },
  { name: 'game-sdk', srcDir: join(ROOT, '..', '..', 'packages', 'game-sdk', 'src'), extraFiles: [join(ROOT, '..', '..', 'packages', 'game-sdk', 'package.json')] },
  { name: 'game-ui',  srcDir: join(ROOT, '..', '..', 'packages', 'game-ui', 'src'), extraFiles: [join(ROOT, '..', '..', 'packages', 'game-ui', 'package.json')] },
  { name: 'copilot-skills',  srcDir: join(ROOT, 'skills', 'copilot') },
  { name: 'designer-skills', srcDir: join(ROOT, 'skills', 'designer') },
];

function collectFiles(dir: string, base: string = dir): TarEntry[] {
  const entries: TarEntry[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      entries.push(...collectFiles(full, base));
    } else {
      entries.push({
        // Always use forward slashes in tar paths (OPFS rejects backslashes on Windows)
        path: relative(base, full).replaceAll('\\', '/'),
        content: new Uint8Array(readFileSync(full)),
      });
    }
  }
  return entries;
}

async function main() {
  const outDir = join(ROOT, 'dist', 'templates');
  const staticDir = join(ROOT, '..', '..', 'apps', 'studio', 'static', 'templates');
  mkdirSync(outDir, { recursive: true });
  mkdirSync(staticDir, { recursive: true });

  const hashes: Record<string, string> = {};

  for (const { name, srcDir, extraFiles } of TEMPLATES) {
    const entries = collectFiles(srcDir);
    // Include extra files (e.g. package.json from parent dir) at archive root
    if (extraFiles) {
      for (const filePath of extraFiles) {
        // Use path.basename equivalent that works on both Windows and Unix
        const fileName = filePath.replace(/\\/g, '/').split('/').pop()!;
        entries.push({
          path: fileName,
          content: new Uint8Array(readFileSync(filePath)),
        });
      }
    }
    const tar = createTar(entries);
    const gz = await gzipAsync(tar);
    const outPath = join(outDir, `${name}.tar.gz`);
    writeFileSync(outPath, gz);
    // Also copy to studio static so they are served at /templates/*.tar.gz
    copyFileSync(outPath, join(staticDir, `${name}.tar.gz`));

    // Compute content hash of the archive
    const hash = createHash('sha256').update(gz as Buffer).digest('hex').slice(0, 12);
    hashes[name] = hash;

    console.log(`${name}: ${entries.length} files → ${outPath} (${gz.length} bytes) [${hash}]`);
  }

  // Generate TypeScript hash file for SimpleModeBridge
  const generatedPath = join(ROOT, '..', '..', 'apps', 'studio', 'src', 'lib', 'simple-mode', 'template-hashes.generated.ts');
  const ts = [
    '// Auto-generated by pack-templates.ts — do not edit manually.',
    `// Generated at: ${new Date().toISOString()}`,
    '',
    'export const TEMPLATE_HASHES: Record<string, string> = {',
    ...Object.entries(hashes).map(([k, v]) => `  '${k}': '${v}',`),
    '} as const;',
    '',
  ].join('\n');
  writeFileSync(generatedPath, ts);
  console.log(`\nGenerated: ${generatedPath}`);
}

main();
