services:
  nginx:
    image: nginx:alpine
    depends_on: [mediawikifarm]
    volumes:
      - ${HOST_CONFIG_DIR}/nginx/wiki.conf:/etc/nginx/conf.d/default.conf:ro
      - wikifarm-wikis:/srv/wikis:ro   # 一次挂载大目录
      - ${HOST_TEMPLATE_DIR}:/template:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.wikifarm.rule=HostRegexp(`^.+\.$ESCAPED_WIKI_HOST$`)
      - traefik.http.routers.wikifarm.entrypoints=websecure
      - traefik.http.routers.wikifarm.service=wikifarm
      - traefik.http.routers.wikifarm.tls.certresolver=cloudflare
      - traefik.http.routers.wikifarm.tls.domains[0].main=*.${WIKI_HOST}
      - traefik.http.services.wikifarm.loadbalancer.server.port=80
      - traefik.http.routers.wikifarm.middlewares=chained-auth
      - traefik.http.routers.wikifarm.priority=1

      - "traefik.http.middlewares.chained-auth.chain.middlewares=wikifarm-auth1,wikifarm-auth2"
      
      - "traefik.http.middlewares.wikifarm-auth1.forwardauth.trustForwardHeader=false"
      - "traefik.http.middlewares.wikifarm-auth1.forwardauth.address=http://nginx/rest.php/wikimanage/v1/auth/check"
      - "traefik.http.middlewares.wikifarm-auth1.forwardauth.authResponseHeaders=X-Auth-User,X-Auth-User-Id,X-Auth-Granted-Right,X-Auth-User-Groups"

      - "traefik.http.middlewares.wikifarm-auth2.forwardauth.trustForwardHeader=false"
      - "traefik.http.middlewares.wikifarm-auth2.forwardauth.address=http://provisioner:8080/manage/v1/visibility/check"

    networks:
      - proxy
      - farm
  
  mediawikifarm:
    image: m4tsuri/pubwikifarm:v1.5
    container_name: mediawikifarm
    environment:
      DATABASE_URL: "mysql://$WIKI_DB_ADMIN_USER:$WIKI_DB_ADMIN_PASSWORD@${WIKI_DB_HOST}/$MAINWIKI_DB_NAME"
      RUST_LOG: info
    volumes:
      - wikifarm-wikis:/srv/wikis:rw
      - wiki-oauth:/oauth:ro
      - wikifarm-config:/config:rw
      - wikifarm-aws:/var/www/.aws
      - ${HOST_TEMPLATE_DIR}:/template:ro
      - ${HOST_CONFIG_DIR}/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ${HOST_CONFIG_DIR}/php-conf/wiki.ini:/usr/local/etc/php/conf.d/wiki.ini:ro
    command: ["/entrypoint.sh"]
    networks:
      - wikinet
      - farm

  redis:
    image: redis:latest
    networks:
      - wikinet
    command: ["bash", "-c", "redis-server --requirepass $$REDIS_PASSWORD"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  provisioner:
    image: m4tsuri/pubwiki-provisioner:v1.9
    depends_on: [mediawikifarm]
    container_name: wikifarm-provisioner
    environment:
      DATABASE_URL: "mysql://$WIKI_DB_ADMIN_USER:$WIKI_DB_ADMIN_PASSWORD@${WIKI_DB_HOST}/$MAINWIKI_DB_NAME"
      REDIS_URL: "redis://:$REDIS_PASSWORD@redis/"
      WIKIFARM_INSTANCE: mediawikifarm
      WIKI_HOST: ${WIKI_HOST}
      WIKI_DB_HOST: ${WIKI_DB_HOST}
      WIKI_SHARED_DB_NAME: ${MAINWIKI_DB_NAME}
      OPENSEARCH_USER: ${OPENSEARCH_USER}
      OPENSEARCH_PORT: ${OPENSEARCH_PORT}
      OPENSEARCH_TRANSPORT: ${OPENSEARCH_TRANSPORT}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
      OPENSEARCH_ENDPOINT: ${OPENSEARCH_ENDPOINT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SERVER: redis
      RUST_LOG: info
      RUST_BACKTRACE: 1
      WIKI_AWS_REGION: ${WIKI_AWS_REGION}
      # DISABLE_ROLLBACK: true
    networks:
      - wikinet
      - proxy
    volumes:
      - wikifarm-wikis:/srv/wikis:rw
      - wiki-oauth:/oauth
      - wikifarm-config:/config
      - ${HOST_TEMPLATE_DIR}:/template:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # Router for creating wiki
      - "traefik.http.routers.provisioner.rule=Host(`${WIKI_HOST}`) && PathPrefix(`/provisioner/`)"
      - "traefik.http.routers.provisioner.entrypoints=websecure"
      - "traefik.http.services.provisioner.loadbalancer.server.port=8080"
      - "traefik.http.routers.provisioner.service=provisioner"
      - "traefik.http.routers.provisioner.tls.certresolver=cloudflare"
      - "traefik.http.routers.provisioner.middlewares=provisioner-auth"

      # Router for managing wiki
      - traefik.http.routers.manager.rule=HostRegexp(`^.+\.$ESCAPED_WIKI_HOST$`) && PathPrefix(`/manage/`)
      - traefik.http.routers.manager.entrypoints=websecure
      - traefik.http.services.manager.loadbalancer.server.port=8080
      - traefik.http.routers.manager.service=manager
      - traefik.http.routers.manager.tls.certresolver=cloudflare
      - traefik.http.routers.manager.tls.domains[0].main=*.${WIKI_HOST}
      - traefik.http.routers.manager.middlewares=wikimanage-auth

      # -- WikiManage Auth Middleware that requires auth user with specific group in sub wiki 
      - "traefik.http.middlewares.wikimanage-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.wikimanage-auth.forwardauth.address=http://nginx/rest.php/wikimanage/v1/auth/check"
      - "traefik.http.middlewares.wikimanage-auth.forwardauth.authResponseHeaders=X-Auth-User,X-Auth-User-Id,X-Auth-Granted-Right,X-Auth-User-Groups"

      # -- WikiFarm Auth Middleware
      - "traefik.http.middlewares.provisioner-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.provisioner-auth.forwardauth.address=http://mainwiki/rest.php/wikifarm/v1/auth/check"
      - "traefik.http.middlewares.provisioner-auth.forwardauth.authResponseHeaders=X-Auth-User,X-Auth-User-Id,X-Auth-Granted-Right"

  mainwiki:
    image: m4tsuri/pubwiki:v1.9
    restart: unless-stopped
    environment: 
      WIKI_SITE_NAME: Pub Wiki
      WIKI_META_NAMESPACE: Pub_Wiki
      WIKI_HOST: ${WIKI_HOST}
      WIKI_LANG: "zh-hans"
      WIKI_ADMIN_USER: ${MAINWIKI_ADMIN_USER}
      WIKI_ADMIN_PASSWORD: ${MAINWIKI_ADMIN_PASSWORD}
      WIKI_DB_ADMIN_PASSWORD: ${WIKI_DB_ADMIN_PASSWORD}
      WIKI_DB_ADMIN_USER: ${WIKI_DB_ADMIN_USER}
      WIKI_DB_HOST: ${WIKI_DB_HOST}
      WIKI_DB_USER: ${MAINWIKI_DB_USER}
      WIKI_DB_PASSWORD: ${MAINWIKI_DB_PASSWORD}
      WIKI_DB_NAME: ${MAINWIKI_DB_NAME}
      WIKI_SMTP_PASSWORD: ${WIKI_SMTP_PASSWORD}
      WIKI_SMTP_HOST: ${WIKI_SMTP_HOST}
      WIKI_SMTP_PORT: ${WIKI_SMTP_PORT}
      WIKI_SMTP_USER: ${WIKI_SMTP_USER}
      WIKI_SMTP_PASSWORD_SENDER: ${WIKI_SMTP_PASSWORD_SENDER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SERVER: redis
      OPENSEARCH_USER: ${OPENSEARCH_USER}
      OPENSEARCH_PORT: ${OPENSEARCH_PORT}
      OPENSEARCH_TRANSPORT: ${OPENSEARCH_TRANSPORT}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
      OPENSEARCH_ENDPOINT: ${OPENSEARCH_ENDPOINT}
    volumes:
      - wiki-oauth:/oauth
      - wiki-images:/var/www/html/images
      - ../../extensions/WikiFarm:/var/www/html/extensions/WikiFarm
      - ../../extensions/OAuthCentralIDCompact:/var/www/html/extensions/OAuthCentralIDCompact
    networks:
      - proxy
      - wikinet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mainwiki.rule=Host(`${WIKI_HOST}`)"
      - "traefik.http.routers.mainwiki.entrypoints=websecure"
      - "traefik.http.services.mainwiki.loadbalancer.server.port=80"
      - "traefik.http.routers.mainwiki.service=mainwiki"
      - "traefik.http.routers.mainwiki.tls.certresolver=cloudflare"


networks:
  proxy:
    name: proxy
    external: true
  wikinet:
    name: wikinet
  farm:

volumes:
  wiki-oauth:
  wikifarm-wikis:
  wikifarm-config:
  wikifarm-aws:
  wiki-images:
  caddy-data:

