services:
  nginx:
    image: nginx:alpine
    depends_on: [mediawikifarm]
    volumes:
      - ${HOST_CONFIG_DIR}/nginx/wiki.conf:/etc/nginx/conf.d/default.conf:ro
      - wikifarm-wikis:/srv/wikis:ro   # 一次挂载大目录
      - ${HOST_TEMPLATE_DIR}:/template:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.wikifarm.rule=HostRegexp(`^.+\.$ESCAPED_WIKI_HOST$`)
      - traefik.http.routers.wikifarm.entrypoints=websecure
      - traefik.http.routers.wikifarm.service=wikifarm
      - traefik.http.routers.wikifarm.tls.certresolver=cloudflare
      - traefik.http.routers.wikifarm.tls.domains[0].main=*.${WIKI_HOST}
      - traefik.http.services.wikifarm.loadbalancer.server.port=80
      - traefik.http.routers.wikifarm.priority=1
    networks:
      - proxy
      - farm
  
  mediawikifarm:
    image: m4tsuri/pubwikifarm:v1.0
    container_name: mediawikifarm
    volumes:
      - wikifarm-wikis:/srv/wikis:rw
      - wikifarm-oauth:/oauth:ro
      - wikifarm-config:/config:rw
      - wikifarm-aws:/var/www/.aws
      - ${HOST_TEMPLATE_DIR}:/template:ro
      - ${HOST_CONFIG_DIR}/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ${HOST_CONFIG_DIR}/php-conf/wiki.ini:/usr/local/etc/php/conf.d/wiki.ini:ro
    networks:
      - wikinet
      - farm

  redis:
    image: redis:latest
    networks:
      - wikinet
    command: ["bash", "-c", "redis-server --requirepass $$REDIS_PASSWORD"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  provisioner:
    image: m4tsuri/pubwiki-provisioner:v1.0
    depends_on: [mediawikifarm]
    container_name: wikifarm-provisioner
    environment:
      DATABASE_URL: "mysql://$WIKI_DB_ADMIN_USER:$WIKI_DB_ADMIN_PASSWORD@${WIKI_DB_HOST}/$MAINWIKI_DB_NAME"
      REDIS_URL: "redis://:$REDIS_PASSWORD@redis/"
      WIKIFARM_INSTANCE: mediawikifarm
      WIKI_HOST: ${WIKI_HOST}
      WIKI_DB_HOST: ${WIKI_DB_HOST}
      WIKI_SHARED_DB_NAME: ${MAINWIKI_DB_NAME}
      OPENSEARCH_USER: ${OPENSEARCH_USER}
      OPENSEARCH_PORT: ${OPENSEARCH_PORT}
      OPENSEARCH_TRANSPORT: ${OPENSEARCH_TRANSPORT}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
      OPENSEARCH_ENDPOINT: ${OPENSEARCH_ENDPOINT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SERVER: redis
      RUST_LOG: debug
      RUST_BACKTRACE: 1
      WIKI_AWS_REGION: ${WIKI_AWS_REGION}
    networks:
      - wikinet
      - proxy
    volumes:
      - wikifarm-wikis:/srv/wikis:rw
      - wikifarm-oauth:/oauth
      - wikifarm-config:/config
      - ${HOST_TEMPLATE_DIR}:/template:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.provisioner.rule=Host(`${WIKI_HOST}`) && (PathPrefix(`/provisioner/`) || PathPrefix(`/manage/`))"
      - "traefik.http.routers.provisioner.entrypoints=websecure"
      - "traefik.http.services.provisioner.loadbalancer.server.port=8080"
      - "traefik.http.routers.provisioner.service=provisioner"
      - "traefik.http.routers.provisioner.tls.certresolver=cloudflare"
      - "traefik.http.routers.provisioner.middlewares=wikifarm-auth"
      - "traefik.http.middlewares.wikifarm-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.wikifarm-auth.forwardauth.address=http://mainwiki/rest.php/wikifarm/v1/auth/check"
      - "traefik.http.middlewares.wikifarm-auth.forwardauth.authResponseHeaders=X-Auth-User,X-Auth-User-Id,X-Auth-Granted-Right"

  mainwiki:
    image: m4tsuri/pubwiki:v1.7
    restart: unless-stopped
    environment: 
      WIKI_SITE_NAME: Pub Wiki
      WIKI_META_NAMESPACE: Pub_Wiki
      WIKI_HOST: ${WIKI_HOST}
      WIKI_LANG: "zh-hans"
      WIKI_ADMIN_USER: ${MAINWIKI_ADMIN_USER}
      WIKI_ADMIN_PASSWORD: ${MAINWIKI_ADMIN_PASSWORD}
      WIKI_DB_ADMIN_PASSWORD: ${WIKI_DB_ADMIN_PASSWORD}
      WIKI_DB_ADMIN_USER: ${WIKI_DB_ADMIN_USER}
      WIKI_DB_HOST: ${WIKI_DB_HOST}
      WIKI_DB_USER: ${MAINWIKI_DB_USER}
      WIKI_DB_PASSWORD: ${MAINWIKI_DB_PASSWORD}
      WIKI_DB_NAME: ${MAINWIKI_DB_NAME}
      WIKI_SMTP_PASSWORD: ${WIKI_SMTP_PASSWORD}
      WIKI_SMTP_HOST: ${WIKI_SMTP_HOST}
      WIKI_SMTP_PORT: ${WIKI_SMTP_PORT}
      WIKI_SMTP_USER: ${WIKI_SMTP_USER}
      WIKI_SMTP_PASSWORD_SENDER: ${WIKI_SMTP_PASSWORD_SENDER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SERVER: redis
    volumes:
      - wiki-images:/var/www/html/images
      - ../../extensions/WikiFarm:/var/www/html/extensions/WikiFarm
    networks:
      - proxy
      - wikinet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.rule=Host(`${WIKI_HOST}`)"
      - "traefik.http.routers.wiki.entrypoints=websecure"
      - "traefik.http.services.wiki.loadbalancer.server.port=80"
      - "traefik.http.routers.wiki.service=wiki"
      - "traefik.http.routers.wiki.tls.certresolver=cloudflare"


networks:
  proxy:
    name: proxy
    external: true
  wikinet:
    name: wikinet
  farm:

volumes:
  wikifarm-oauth:
  wikifarm-wikis:
  wikifarm-config:
  wikifarm-aws:
  wiki-images:
  caddy-data:

