/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * PubWiki API
 * PubWiki Backend API

## 认证说明

本 API 使用 [Better-Auth](https://www.better-auth.com/) 进行身份认证。

**重要**: 认证相关的 API（注册、登录、会话管理等）不包含在此 OpenAPI 规范中。
客户端应该使用 `better-auth/client` 库进行认证操作，而不是通过此处定义的 OpenAPI 客户端。

### 客户端认证示例

```typescript
import { createAuthClient } from 'better-auth/client';

const authClient = createAuthClient({
  baseURL: 'https://api.pubwiki.com',
});

// 注册
await authClient.signUp.email({
  email: 'user@example.com',
  password: 'password123',
  name: 'User Name',
  username: 'username',
});

// 登录
await authClient.signIn.email({
  email: 'user@example.com',
  password: 'password123',
});

// 获取会话
const session = await authClient.getSession();
```

认证成功后，Better-Auth 会自动设置 session cookie，后续请求会自动携带认证信息。

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary 健康检查
 */
export const HealthCheckResponse = zod.object({
  "message": zod.string(),
  "version": zod.string()
})


/**
 * 需要通过 Better-Auth session cookie 认证。使用 better-auth/client 登录后会自动设置 cookie。
 * @summary 获取当前用户信息
 */
export const getMeResponseUserUsernameMin = 3;
export const getMeResponseUserUsernameMax = 50;



export const GetMeResponse = zod.object({
  "user": zod.object({
  "id": zod.uuid(),
  "username": zod.string().min(getMeResponseUserUsernameMin).max(getMeResponseUserUsernameMax),
  "email": zod.email(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish(),
  "bio": zod.string().nullish(),
  "website": zod.url().nullish(),
  "location": zod.string().nullish(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})
})


/**
 * @summary 更新当前用户 Profile
 */
export const updateProfileBodyDisplayNameMax = 100;

export const updateProfileBodyAvatarUrlMax = 500;

export const updateProfileBodyWebsiteMax = 255;

export const updateProfileBodyLocationMax = 100;



export const UpdateProfileBody = zod.object({
  "displayName": zod.string().max(updateProfileBodyDisplayNameMax).optional(),
  "avatarUrl": zod.url().max(updateProfileBodyAvatarUrlMax).optional(),
  "bio": zod.string().optional(),
  "website": zod.url().max(updateProfileBodyWebsiteMax).optional(),
  "location": zod.string().max(updateProfileBodyLocationMax).optional()
})

export const updateProfileResponseUserUsernameMin = 3;
export const updateProfileResponseUserUsernameMax = 50;



export const UpdateProfileResponse = zod.object({
  "message": zod.string(),
  "user": zod.object({
  "id": zod.uuid(),
  "username": zod.string().min(updateProfileResponseUserUsernameMin).max(updateProfileResponseUserUsernameMax),
  "email": zod.email(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish(),
  "bio": zod.string().nullish(),
  "website": zod.url().nullish(),
  "location": zod.string().nullish(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})
})


/**
 * 获取指定用户拥有的所有 Artifact。
返回结果基于可发现性（isListed）过滤：
- 查看他人：只能看到已列出的 artifact
- 查看自己：可以看到所有 artifact

 * @summary 获取用户的 Artifact 列表
 */
export const GetUserArtifactsParams = zod.object({
  "userId": zod.uuid().describe('用户 ID')
})

export const getUserArtifactsQueryPageDefault = 1;

export const getUserArtifactsQueryLimitDefault = 20;
export const getUserArtifactsQueryLimitMax = 100;

export const getUserArtifactsQuerySortByDefault = `createdAt`;export const getUserArtifactsQuerySortOrderDefault = `desc`;

export const GetUserArtifactsQueryParams = zod.object({
  "page": zod.number().min(1).default(getUserArtifactsQueryPageDefault).describe('页码'),
  "limit": zod.number().min(1).max(getUserArtifactsQueryLimitMax).default(getUserArtifactsQueryLimitDefault).describe('每页数量'),
  "sortBy": zod.enum(['createdAt', 'updatedAt', 'viewCount', 'favCount']).default(getUserArtifactsQuerySortByDefault).describe('排序字段'),
  "sortOrder": zod.enum(['asc', 'desc']).default(getUserArtifactsQuerySortOrderDefault).describe('排序方向')
})


export const getUserArtifactsResponsePaginationLimitMax = 100;



export const GetUserArtifactsResponse = zod.object({
  "artifacts": zod.array(zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "thumbnailUrl": zod.url().nullish(),
  "license": zod.string().nullish(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({}),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "tags": zod.array(zod.object({
  "slug": zod.string().describe('Tag slug (primary key)'),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "color": zod.string().nullish().describe('颜色代码 #RRGGBB')
})).optional(),
  "stats": zod.object({
  "viewCount": zod.number().optional().describe('浏览次数'),
  "favCount": zod.number().optional().describe('收藏次数'),
  "refCount": zod.number().optional().describe('引用次数（被 fork 次数）'),
  "downloadCount": zod.number().optional().describe('下载次数')
}).optional().describe('Artifact 统计信息')
})),
  "pagination": zod.object({
  "page": zod.number().min(1),
  "limit": zod.number().min(1).max(getUserArtifactsResponsePaginationLimitMax),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * 获取指定用户拥有的所有 Project。
返回结果基于可发现性（isListed）过滤：
- 查看他人：只能看到已列出的 project
- 查看自己：可以看到所有 project

 * @summary 获取用户的 Project 列表
 */
export const GetUserProjectsParams = zod.object({
  "userId": zod.uuid().describe('用户 ID')
})

export const getUserProjectsQueryPageDefault = 1;

export const getUserProjectsQueryLimitDefault = 20;
export const getUserProjectsQueryLimitMax = 100;

export const getUserProjectsQuerySortByDefault = `createdAt`;export const getUserProjectsQuerySortOrderDefault = `desc`;

export const GetUserProjectsQueryParams = zod.object({
  "page": zod.number().min(1).default(getUserProjectsQueryPageDefault).describe('页码'),
  "limit": zod.number().min(1).max(getUserProjectsQueryLimitMax).default(getUserProjectsQueryLimitDefault).describe('每页数量'),
  "role": zod.enum(['owner', 'maintainer']).optional().describe('按用户角色过滤（owner 或 maintainer）'),
  "sortBy": zod.enum(['createdAt', 'updatedAt']).default(getUserProjectsQuerySortByDefault).describe('排序字段'),
  "sortOrder": zod.enum(['asc', 'desc']).default(getUserProjectsQuerySortOrderDefault).describe('排序方向')
})


export const getUserProjectsResponsePaginationLimitMax = 100;



export const GetUserProjectsResponse = zod.object({
  "projects": zod.array(zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "topic": zod.string().describe('Project 的 hashtag'),
  "description": zod.string().nullish(),
  "license": zod.string().nullish(),
  "coverUrls": zod.array(zod.url()).optional().describe('封面图片 URL 数组'),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({}),
  "owner": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "artifactCount": zod.number().optional().describe('关联 artifact 数量')
})),
  "pagination": zod.object({
  "page": zod.number().min(1),
  "limit": zod.number().min(1).max(getUserProjectsResponsePaginationLimitMax),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * 获取所有公开的 Artifact，支持按类型和标签过滤，支持排序
 * @summary 获取公开 Artifact 列表
 */
export const listArtifactsQueryPageDefault = 1;

export const listArtifactsQueryLimitDefault = 20;
export const listArtifactsQueryLimitMax = 100;

export const listArtifactsQuerySortByDefault = `createdAt`;export const listArtifactsQuerySortOrderDefault = `desc`;

export const ListArtifactsQueryParams = zod.object({
  "page": zod.number().min(1).default(listArtifactsQueryPageDefault).describe('页码'),
  "limit": zod.number().min(1).max(listArtifactsQueryLimitMax).default(listArtifactsQueryLimitDefault).describe('每页数量'),
  "tag.include": zod.array(zod.string()).optional().describe('包含的标签 slug 列表（AND 逻辑）'),
  "tag.exclude": zod.array(zod.string()).optional().describe('排除的标签 slug 列表'),
  "sortBy": zod.enum(['createdAt', 'updatedAt', 'viewCount', 'favCount']).default(listArtifactsQuerySortByDefault).describe('排序字段'),
  "sortOrder": zod.enum(['asc', 'desc']).default(listArtifactsQuerySortOrderDefault).describe('排序方向')
})


export const listArtifactsResponsePaginationLimitMax = 100;



export const ListArtifactsResponse = zod.object({
  "artifacts": zod.array(zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "thumbnailUrl": zod.url().nullish(),
  "license": zod.string().nullish(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({}),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "tags": zod.array(zod.object({
  "slug": zod.string().describe('Tag slug (primary key)'),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "color": zod.string().nullish().describe('颜色代码 #RRGGBB')
})).optional(),
  "stats": zod.object({
  "viewCount": zod.number().optional().describe('浏览次数'),
  "favCount": zod.number().optional().describe('收藏次数'),
  "refCount": zod.number().optional().describe('引用次数（被 fork 次数）'),
  "downloadCount": zod.number().optional().describe('下载次数')
}).optional().describe('Artifact 统计信息')
})),
  "pagination": zod.object({
  "page": zod.number().min(1),
  "limit": zod.number().min(1).max(listArtifactsResponsePaginationLimitMax),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * 一步发布：提交完整的 node version 数据 + artifact 元数据，服务端内部同步 node versions 并创建 artifact version。

**创建/更新模式：** 通过 metadata.artifactId 判断：
- 该 ID 不存在于数据库中：创建新 artifact
- 该 ID 存在且 owner 是当前用户：追加新版本（append-only）
- 该 ID 存在但 owner 不是当前用户：返回 403 Forbidden

使用 multipart/form-data 格式：
- metadata: JSON 格式的 artifact 基本信息
- nodes: JSON 数组，包含完整的 node version 数据（仅 ARTIFACT_NODE_TYPES，不含 SAVE）
- edges: JSON 数组，节点间连接关系
- vfs[{commit}]: VFS 节点的 tar.gz 归档文件，key 中 commit 对应 nodes 中的 VFS 节点版本
- save[{commit}]: Save 的二进制数据，key 中 commit 对应 saves 中的 save 版本
- homepage: 可选的主页 Markdown 文件

注意：vfs[xxx] 和 save[xxx] 是动态 key，在 OpenAPI 中通过 additionalProperties 描述。

 * @summary 创建或更新 Artifact（包含完整的 Node Version 数据）
 */
export const createArtifactBodyMetadataNameMax = 100;

export const createArtifactBodyMetadataIsListedDefault = true;export const createArtifactBodyMetadataThumbnailUrlMax = 500;

export const createArtifactBodyMetadataLicenseMax = 50;

export const createArtifactBodyMetadataRepositoryUrlMax = 500;

export const createArtifactBodyMetadataVersionRegExp = new RegExp('^\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9]+)?$');
export const createArtifactBodyMetadataSavesItemIsListedDefault = false;export const createArtifactBodyNodesItemContentOneGenerationConfigTemperatureMin = 0;
export const createArtifactBodyNodesItemContentOneGenerationConfigTemperatureMax = 2;

export const createArtifactBodyNodesItemContentFourEntryFileDefault = `index.html`;

export const CreateArtifactBody = zod.object({
  "metadata": zod.object({
  "artifactId": zod.uuid().describe('Artifact ID，必须是客户端生成的 UUID（使用 crypto.randomUUID()）。\n服务端会检查此 ID 是否已存在于数据库中：\n- 不存在：创建新 artifact\n- 存在且 owner 是当前用户：更新已有 artifact\n- 存在但 owner 不是当前用户：返回 403 Forbidden\n'),
  "commit": zod.string().describe('Artifact version 的 commit hash，由客户端基于内容确定性计算。\n客户端应对 (artifactId + parentCommit + sorted nodes + sorted edges) 取 hash。\n通过包含 artifactId 和 parentCommit 形成链状结构，保证全局唯一性。\n'),
  "parentCommit": zod.string().nullish().describe('上一个版本的 commit hash，用于形成链状结构保证 commit 全局唯一性。\n创建新 artifact 时为 null，更新已有 artifact 时为当前版本的 commit hash。\n客户端在计算 commit 时必须包含此字段。\n'),
  "name": zod.string().min(1).max(createArtifactBodyMetadataNameMax),
  "description": zod.string().optional(),
  "isListed": zod.boolean().default(createArtifactBodyMetadataIsListedDefault).describe('是否在公开列表中可见（可发现性）'),
  "thumbnailUrl": zod.url().max(createArtifactBodyMetadataThumbnailUrlMax).optional(),
  "license": zod.string().max(createArtifactBodyMetadataLicenseMax).optional(),
  "repositoryUrl": zod.url().max(createArtifactBodyMetadataRepositoryUrlMax).optional(),
  "version": zod.string().regex(createArtifactBodyMetadataVersionRegExp).optional().describe('Semver 版本号'),
  "changelog": zod.string().optional(),
  "tags": zod.array(zod.string()).optional().describe('Tag slugs 数组'),
  "entrypoint": zod.object({
  "saveCommit": zod.string().describe('Save 的 commit hash，指定启动时加载的存档'),
  "sandboxNodeId": zod.uuid().describe('沙箱节点 ID')
}).optional(),
  "commitTags": zod.array(zod.string()).optional().describe('用户可分配的版本标签列表（如 [\"stable\", \"beta\", \"v1.0\"]）。\n同一 artifact 内每个 tag 唯一，一个 commit 可以有多个 tag。\n如果某个 tag 已被其他 commit 使用，则自动从旧 commit 上移除（override 语义）。\n'),
  "saves": zod.array(zod.object({
  "stateNodeId": zod.uuid().describe('关联的 STATE 节点 ID'),
  "commit": zod.string().describe('Save 版本的 commit hash'),
  "contentHash": zod.string().describe('Save 内容的指纹'),
  "parent": zod.string().nullish().describe('父 save 的 commit hash'),
  "title": zod.string().optional().describe('Save 标题'),
  "description": zod.string().optional().describe('Save 描述'),
  "isListed": zod.boolean().default(createArtifactBodyMetadataSavesItemIsListedDefault).describe('是否在公开列表中可见（可发现性）')
}).describe('和 artifact 一起创建的 save 数据。\n服务端会从 artifact 的 nodes 数组中自动获取 stateNodeCommit，\n并使用 artifact 的 commit 作为 sourceArtifactCommit。\n')).optional().describe('和 artifact 同时创建的 save 列表（解决 save 和 artifact 的循环依赖）。\nSave 的二进制数据通过 save[{commit}] 形式在 multipart form 中上传。\n服务端会先创建 save，然后再验证 STATE 节点内容的合法性。\n')
}),
  "nodes": zod.array(zod.object({
  "nodeId": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('版本 hash'),
  "parent": zod.string().nullish().describe('父版本 commit hash'),
  "type": zod.enum(['PROMPT', 'INPUT', 'GENERATED', 'VFS', 'LOADER', 'SANDBOX', 'STATE']),
  "name": zod.string().optional(),
  "contentHash": zod.string().describe('内容指纹'),
  "content": zod.union([zod.object({
  "type": zod.enum(['INPUT']),
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("TextBlock"),
  "value": zod.string()
}),zod.object({
  "type": zod.literal("RefTagBlock"),
  "name": zod.string().describe('引用的节点名称')
})])),
  "mountpoints": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "path": zod.string().describe('挂载路径')
})).optional(),
  "generationConfig": zod.object({
  "model": zod.string().optional().describe('生成使用的模型（空=使用全局设置）'),
  "temperature": zod.number().min(createArtifactBodyNodesItemContentOneGenerationConfigTemperatureMin).max(createArtifactBodyNodesItemContentOneGenerationConfigTemperatureMax).optional().describe('生成温度'),
  "schema": zod.string().optional().describe('结构化输出的 JSON Schema')
}).optional()
}),zod.object({
  "type": zod.enum(['PROMPT']),
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("TextBlock"),
  "value": zod.string()
}),zod.object({
  "type": zod.literal("RefTagBlock"),
  "name": zod.string().describe('引用的节点名称')
})]))
}),zod.object({
  "type": zod.enum(['GENERATED']),
  "blocks": zod.array(zod.object({
  "id": zod.string().describe('Unique block ID'),
  "type": zod.enum(['text', 'markdown', 'code', 'tool_call', 'tool_result', 'image', 'reasoning']).describe('Message block types:\n- text: Plain text\n- markdown: Markdown content\n- code: Code block\n- tool_call: Tool call request\n- tool_result: Tool call result\n- image: Image (reserved for future)\n- reasoning: Reasoning content\n'),
  "content": zod.string().describe('Block content'),
  "metadata": zod.record(zod.string(), zod.unknown()).optional().describe('Additional metadata'),
  "toolCallId": zod.string().optional().describe('Tool call ID (for tool_call and tool_result types)'),
  "toolName": zod.string().optional().describe('Tool name (for tool_call type)'),
  "toolArgs": zod.unknown().optional().describe('Tool arguments (for tool_call type)'),
  "toolStatus": zod.enum(['pending', 'running', 'completed', 'error']).optional().describe('Tool call execution status')
})),
  "inputRef": zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
}),
  "promptRefs": zod.array(zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
})).optional(),
  "indirectPromptRefs": zod.array(zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
})).optional(),
  "inputVfsRef": zod.object({
  "nodeId": zod.uuid().describe('VFS 节点 ID'),
  "commit": zod.string().describe('VFS 状态的 commit hash')
}).nullish(),
  "outputVfsId": zod.uuid().nullish(),
  "postGenerationCommit": zod.string().nullish().describe('Post-generation commit hash - recorded after file modifications are complete')
}),zod.object({
  "type": zod.enum(['SANDBOX']),
  "entryFile": zod.string().default(createArtifactBodyNodesItemContentFourEntryFileDefault)
}),zod.object({
  "type": zod.enum(['LOADER']),
  "mountpoints": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "path": zod.string().describe('挂载路径')
})).optional()
}),zod.object({
  "type": zod.enum(['STATE']),
  "name": zod.string().describe('状态节点的名称'),
  "description": zod.string().optional().describe('状态节点的描述')
}),zod.object({
  "type": zod.enum(['VFS']),
  "projectId": zod.string().describe('所属项目 ID'),
  "mounts": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "sourceNodeId": zod.uuid().describe('源 VFS 节点 ID'),
  "mountPath": zod.string().describe('挂载路径'),
  "sourceCommit": zod.string().optional().describe('源 VFS 版本 commit hash')
})).optional().describe('VfsMountConfig[] 挂载配置'),
  "fileCount": zod.number().optional().describe('文件总数'),
  "totalSize": zod.number().optional().describe('总大小 (bytes)'),
  "fileTree": zod.array(zod.object({
  "path": zod.string().describe('文件路径'),
  "size": zod.number().optional().describe('文件大小 (bytes)'),
  "mimeType": zod.string().optional().describe('MIME 类型')
})).optional().describe('文件目录树'),
  "files": zod.array(zod.object({
  "path": zod.string().describe('文件路径'),
  "size": zod.number().optional().describe('文件大小 (bytes)'),
  "mimeType": zod.string().optional().describe('MIME 类型')
})).optional().describe('文件列表（用于 API 验证）')
})]),
  "message": zod.string().optional().describe('Commit 消息'),
  "tag": zod.string().optional().describe('Semver 标签'),
  "isListed": zod.boolean().optional().describe('是否在公开列表中可见（可发现性）'),
  "refs": zod.array(zod.object({
  "targetNodeId": zod.string(),
  "targetCommit": zod.string(),
  "refType": zod.enum(['input', 'prompt', 'indirect_prompt', 'input_vfs', 'output_vfs']).describe('Type of reference between node versions (lineage tracking).\n- input: GENERATED\'s trigger input (INPUT node version)\n- prompt: GENERATED\'s direct prompt reference (PROMPT node version)\n- indirect_prompt: GENERATED\'s indirect prompt reference\n- input_vfs: Pre-generation VFS snapshot reference\n- output_vfs: Post-generation associated VFS node version\n')
})).optional().describe('血统引用（主要用于 GENERATED 节点）'),
  "position": zod.object({
  "x": zod.number().optional(),
  "y": zod.number().optional()
}).optional()
}).describe('完整的 node version 数据，用于在创建 artifact 时一并同步节点版本。\n所有节点的版本数据将通过 artifact 创建接口一次性提交。\n')),
  "edges": zod.array(zod.object({
  "source": zod.uuid(),
  "target": zod.uuid(),
  "sourceHandle": zod.string().optional(),
  "targetHandle": zod.string().optional()
})),
  "homepage": zod.instanceof(File).optional().describe('可选的主页 Markdown 文件，将被渲染为 HTML 后存储。')
})

export const CreateArtifactResponse = zod.object({
  "message": zod.string(),
  "artifact": zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "thumbnailUrl": zod.url().nullish(),
  "license": zod.string().nullish(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({}),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "tags": zod.array(zod.object({
  "slug": zod.string().describe('Tag slug (primary key)'),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "color": zod.string().nullish().describe('颜色代码 #RRGGBB')
})).optional(),
  "stats": zod.object({
  "viewCount": zod.number().optional().describe('浏览次数'),
  "favCount": zod.number().optional().describe('收藏次数'),
  "refCount": zod.number().optional().describe('引用次数（被 fork 次数）'),
  "downloadCount": zod.number().optional().describe('下载次数')
}).optional().describe('Artifact 统计信息')
})
})


/**
 * 增量更新：客户端提交 baseCommit 和变更内容（新增/删除 nodes/edges），
服务端将基准版本的完整 graph 与 patch 合并后创建新版本。

适用于只修改了部分节点的场景，避免重新提交所有节点数据。
注意：新增的节点需要包含完整的 node version 数据。

如果没有 graph 变更且不传 commit，则为 metadata-only 更新：
直接修改 baseCommit 版本的元数据（version, changelog, commitTags, entrypoint 等），
不创建新版本。

 * @summary 基于已有版本和增量补丁创建新 Artifact 版本
 */
export const patchArtifactBodyMetadataNameMax = 100;

export const patchArtifactBodyMetadataVersionRegExp = new RegExp('^\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9]+)?$');
export const patchArtifactBodyMetadataAddNodesItemContentOneGenerationConfigTemperatureMin = 0;
export const patchArtifactBodyMetadataAddNodesItemContentOneGenerationConfigTemperatureMax = 2;

export const patchArtifactBodyMetadataAddNodesItemContentFourEntryFileDefault = `index.html`;export const patchArtifactBodyMetadataSavesItemIsListedDefault = false;

export const PatchArtifactBody = zod.object({
  "metadata": zod.object({
  "artifactId": zod.uuid().describe('要更新的 Artifact ID'),
  "baseCommit": zod.string().describe('基准版本的 commit hash'),
  "commit": zod.string().optional().describe('新版本的 commit hash，由客户端基于合并后的完整 graph 确定性计算。\n计算方式与 POST \/artifacts 一致：hash(artifactId, parentCommit, nodes, edges)\n其中 parentCommit 为基准版本（即 baseCommit）的 commit hash。\n'),
  "name": zod.string().min(1).max(patchArtifactBodyMetadataNameMax).optional(),
  "description": zod.string().optional(),
  "isListed": zod.boolean().optional().describe('是否在公开列表中可见（可发现性）'),
  "version": zod.string().regex(patchArtifactBodyMetadataVersionRegExp).optional().describe('Semver 版本号'),
  "changelog": zod.string().optional(),
  "commitTags": zod.array(zod.string()).optional().describe('可选版本标签列表'),
  "entrypoint": zod.object({
  "saveCommit": zod.string().describe('Save 的 commit hash，指定启动时加载的存档'),
  "sandboxNodeId": zod.uuid().describe('沙箱节点 ID')
}).optional(),
  "addNodes": zod.array(zod.object({
  "nodeId": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('版本 hash'),
  "parent": zod.string().nullish().describe('父版本 commit hash'),
  "type": zod.enum(['PROMPT', 'INPUT', 'GENERATED', 'VFS', 'LOADER', 'SANDBOX', 'STATE']),
  "name": zod.string().optional(),
  "contentHash": zod.string().describe('内容指纹'),
  "content": zod.union([zod.object({
  "type": zod.enum(['INPUT']),
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("TextBlock"),
  "value": zod.string()
}),zod.object({
  "type": zod.literal("RefTagBlock"),
  "name": zod.string().describe('引用的节点名称')
})])),
  "mountpoints": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "path": zod.string().describe('挂载路径')
})).optional(),
  "generationConfig": zod.object({
  "model": zod.string().optional().describe('生成使用的模型（空=使用全局设置）'),
  "temperature": zod.number().min(patchArtifactBodyMetadataAddNodesItemContentOneGenerationConfigTemperatureMin).max(patchArtifactBodyMetadataAddNodesItemContentOneGenerationConfigTemperatureMax).optional().describe('生成温度'),
  "schema": zod.string().optional().describe('结构化输出的 JSON Schema')
}).optional()
}),zod.object({
  "type": zod.enum(['PROMPT']),
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("TextBlock"),
  "value": zod.string()
}),zod.object({
  "type": zod.literal("RefTagBlock"),
  "name": zod.string().describe('引用的节点名称')
})]))
}),zod.object({
  "type": zod.enum(['GENERATED']),
  "blocks": zod.array(zod.object({
  "id": zod.string().describe('Unique block ID'),
  "type": zod.enum(['text', 'markdown', 'code', 'tool_call', 'tool_result', 'image', 'reasoning']).describe('Message block types:\n- text: Plain text\n- markdown: Markdown content\n- code: Code block\n- tool_call: Tool call request\n- tool_result: Tool call result\n- image: Image (reserved for future)\n- reasoning: Reasoning content\n'),
  "content": zod.string().describe('Block content'),
  "metadata": zod.record(zod.string(), zod.unknown()).optional().describe('Additional metadata'),
  "toolCallId": zod.string().optional().describe('Tool call ID (for tool_call and tool_result types)'),
  "toolName": zod.string().optional().describe('Tool name (for tool_call type)'),
  "toolArgs": zod.unknown().optional().describe('Tool arguments (for tool_call type)'),
  "toolStatus": zod.enum(['pending', 'running', 'completed', 'error']).optional().describe('Tool call execution status')
})),
  "inputRef": zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
}),
  "promptRefs": zod.array(zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
})).optional(),
  "indirectPromptRefs": zod.array(zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
})).optional(),
  "inputVfsRef": zod.object({
  "nodeId": zod.uuid().describe('VFS 节点 ID'),
  "commit": zod.string().describe('VFS 状态的 commit hash')
}).nullish(),
  "outputVfsId": zod.uuid().nullish(),
  "postGenerationCommit": zod.string().nullish().describe('Post-generation commit hash - recorded after file modifications are complete')
}),zod.object({
  "type": zod.enum(['SANDBOX']),
  "entryFile": zod.string().default(patchArtifactBodyMetadataAddNodesItemContentFourEntryFileDefault)
}),zod.object({
  "type": zod.enum(['LOADER']),
  "mountpoints": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "path": zod.string().describe('挂载路径')
})).optional()
}),zod.object({
  "type": zod.enum(['STATE']),
  "name": zod.string().describe('状态节点的名称'),
  "description": zod.string().optional().describe('状态节点的描述')
}),zod.object({
  "type": zod.enum(['VFS']),
  "projectId": zod.string().describe('所属项目 ID'),
  "mounts": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "sourceNodeId": zod.uuid().describe('源 VFS 节点 ID'),
  "mountPath": zod.string().describe('挂载路径'),
  "sourceCommit": zod.string().optional().describe('源 VFS 版本 commit hash')
})).optional().describe('VfsMountConfig[] 挂载配置'),
  "fileCount": zod.number().optional().describe('文件总数'),
  "totalSize": zod.number().optional().describe('总大小 (bytes)'),
  "fileTree": zod.array(zod.object({
  "path": zod.string().describe('文件路径'),
  "size": zod.number().optional().describe('文件大小 (bytes)'),
  "mimeType": zod.string().optional().describe('MIME 类型')
})).optional().describe('文件目录树'),
  "files": zod.array(zod.object({
  "path": zod.string().describe('文件路径'),
  "size": zod.number().optional().describe('文件大小 (bytes)'),
  "mimeType": zod.string().optional().describe('MIME 类型')
})).optional().describe('文件列表（用于 API 验证）')
})]),
  "message": zod.string().optional().describe('Commit 消息'),
  "tag": zod.string().optional().describe('Semver 标签'),
  "isListed": zod.boolean().optional().describe('是否在公开列表中可见（可发现性）'),
  "refs": zod.array(zod.object({
  "targetNodeId": zod.string(),
  "targetCommit": zod.string(),
  "refType": zod.enum(['input', 'prompt', 'indirect_prompt', 'input_vfs', 'output_vfs']).describe('Type of reference between node versions (lineage tracking).\n- input: GENERATED\'s trigger input (INPUT node version)\n- prompt: GENERATED\'s direct prompt reference (PROMPT node version)\n- indirect_prompt: GENERATED\'s indirect prompt reference\n- input_vfs: Pre-generation VFS snapshot reference\n- output_vfs: Post-generation associated VFS node version\n')
})).optional().describe('血统引用（主要用于 GENERATED 节点）'),
  "position": zod.object({
  "x": zod.number().optional(),
  "y": zod.number().optional()
}).optional()
}).describe('完整的 node version 数据，用于在创建 artifact 时一并同步节点版本。\n所有节点的版本数据将通过 artifact 创建接口一次性提交。\n')).optional().describe('新增或更新的节点（nodeId 已存在则更新该节点的 commit，否则新增）'),
  "removeNodeIds": zod.array(zod.uuid()).optional().describe('需要移除的节点 ID 列表'),
  "addEdges": zod.array(zod.object({
  "source": zod.uuid(),
  "target": zod.uuid(),
  "sourceHandle": zod.string().optional(),
  "targetHandle": zod.string().optional()
})).optional().describe('新增的边'),
  "removeEdges": zod.array(zod.object({
  "source": zod.uuid(),
  "target": zod.uuid(),
  "sourceHandle": zod.string().optional(),
  "targetHandle": zod.string().optional()
})).optional().describe('需要移除的边（通过 source + target 匹配）'),
  "saves": zod.array(zod.object({
  "stateNodeId": zod.uuid().describe('关联的 STATE 节点 ID'),
  "commit": zod.string().describe('Save 版本的 commit hash'),
  "contentHash": zod.string().describe('Save 内容的指纹'),
  "parent": zod.string().nullish().describe('父 save 的 commit hash'),
  "title": zod.string().optional().describe('Save 标题'),
  "description": zod.string().optional().describe('Save 描述'),
  "isListed": zod.boolean().default(patchArtifactBodyMetadataSavesItemIsListedDefault).describe('是否在公开列表中可见（可发现性）')
}).describe('和 artifact 一起创建的 save 数据。\n服务端会从 artifact 的 nodes 数组中自动获取 stateNodeCommit，\n并使用 artifact 的 commit 作为 sourceArtifactCommit。\n')).optional().describe('和 patch 同时创建的 save 列表。\nSave 的二进制数据通过 save[{commit}] 形式在 multipart form 中上传。\n')
}).describe('基于已有的 commit 和增量补丁创建新的 artifact 版本。\n客户端提交 baseCommit（基准版本）和需要变更的 nodes\/edges，\n服务端将基准版本的完整 graph 与 patch 合并后创建新版本。\n\n如果没有 graph 变更（addNodes\/removeNodeIds\/addEdges\/removeEdges 全部为空或不传），\n且不传 commit，则为 metadata-only 更新：直接修改 baseCommit 版本的元数据，不创建新版本。\n'),
  "homepage": zod.instanceof(File).optional().describe('可选的主页 Markdown 文件')
})

export const PatchArtifactResponse = zod.object({
  "message": zod.string(),
  "artifact": zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "thumbnailUrl": zod.url().nullish(),
  "license": zod.string().nullish(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({}),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "tags": zod.array(zod.object({
  "slug": zod.string().describe('Tag slug (primary key)'),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "color": zod.string().nullish().describe('颜色代码 #RRGGBB')
})).optional(),
  "stats": zod.object({
  "viewCount": zod.number().optional().describe('浏览次数'),
  "favCount": zod.number().optional().describe('收藏次数'),
  "refCount": zod.number().optional().describe('引用次数（被 fork 次数）'),
  "downloadCount": zod.number().optional().describe('下载次数')
}).optional().describe('Artifact 统计信息')
}),
  "versionCreated": zod.boolean().describe('是否创建了新版本（false 表示仅更新了 metadata）')
})


/**
 * 获取指定 Artifact 的只读主页 HTML 内容。
HTML 内容存储在 R2 中，存储 key 由 artifactId 派生。
访问权限由 ACL 系统控制，无权访问时返回 403。

 * @summary 获取 Artifact 主页 HTML
 */
export const GetArtifactHomepageParams = zod.object({
  "artifactId": zod.uuid().describe('Artifact ID')
})


/**
 * 获取指定 Artifact 的谱系（依赖和派生关系）。
支持递归查询多代父/子关系，可通过 parentDepth 和 childDepth 控制递归深度。
返回的每个条目包含 parentId 字段，用于在前端构建树状结构。
访问权限由 ACL 系统控制，无权访问时返回 403。

 * @summary 获取 Artifact 的谱系信息
 */
export const GetArtifactLineageParams = zod.object({
  "artifactId": zod.uuid().describe('Artifact ID')
})





export const GetArtifactLineageQueryParams = zod.object({
  "parentDepth": zod.number().min(1).optional().describe('向上追溯父代的深度（1=直接父代，2=父代+祖父代...）。不指定则无限递归。'),
  "commit": zod.string().optional().describe('指定要查询谱系的版本 commit hash。\n不指定则使用 artifact 的当前版本（currentVersionId）。\n'),
  "childDepth": zod.number().min(1).optional().describe('向下追溯子代的深度（1=直接子代，2=子代+孙代...）。不指定则无限递归。')
})

export const GetArtifactLineageResponse = zod.object({
  "parents": zod.array(zod.object({
  "artifactId": zod.uuid(),
  "name": zod.string(),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "thumbnailUrl": zod.url().nullish(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}).optional()
})).describe('此 Artifact 依赖的父 Artifact'),
  "children": zod.array(zod.object({
  "artifactId": zod.uuid(),
  "name": zod.string(),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "thumbnailUrl": zod.url().nullish(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}).optional()
})).describe('依赖此 Artifact 的子 Artifact')
})


/**
 * 获取 artifact 的完整节点和边列表。
访问权限由 ACL 系统控制，无权访问时返回 403。

 * @summary 获取 Artifact 节点图结构
 */
export const GetArtifactGraphParams = zod.object({
  "artifactId": zod.uuid()
})

export const getArtifactGraphQueryVersionDefault = `latest`;

export const GetArtifactGraphQueryParams = zod.object({
  "version": zod.string().default(getArtifactGraphQueryVersionDefault).describe('artifact 版本哈希、commitTag 或 \"latest\"')
})

export const getArtifactGraphResponseNodesItemContentOneGenerationConfigTemperatureMin = 0;
export const getArtifactGraphResponseNodesItemContentOneGenerationConfigTemperatureMax = 2;

export const getArtifactGraphResponseNodesItemContentFourEntryFileDefault = `index.html`;

export const GetArtifactGraphResponse = zod.object({
  "nodes": zod.array(zod.object({
  "id": zod.uuid(),
  "type": zod.enum(['PROMPT', 'INPUT', 'GENERATED', 'VFS', 'LOADER', 'SANDBOX', 'STATE']),
  "commit": zod.string().describe('节点版本的 commit hash'),
  "contentHash": zod.string().describe('节点内容的指纹'),
  "name": zod.string().nullish(),
  "position": zod.object({
  "x": zod.number().optional(),
  "y": zod.number().optional()
}).optional(),
  "content": zod.union([zod.object({
  "type": zod.enum(['INPUT']),
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("TextBlock"),
  "value": zod.string()
}),zod.object({
  "type": zod.literal("RefTagBlock"),
  "name": zod.string().describe('引用的节点名称')
})])),
  "mountpoints": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "path": zod.string().describe('挂载路径')
})).optional(),
  "generationConfig": zod.object({
  "model": zod.string().optional().describe('生成使用的模型（空=使用全局设置）'),
  "temperature": zod.number().min(getArtifactGraphResponseNodesItemContentOneGenerationConfigTemperatureMin).max(getArtifactGraphResponseNodesItemContentOneGenerationConfigTemperatureMax).optional().describe('生成温度'),
  "schema": zod.string().optional().describe('结构化输出的 JSON Schema')
}).optional()
}),zod.object({
  "type": zod.enum(['PROMPT']),
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("TextBlock"),
  "value": zod.string()
}),zod.object({
  "type": zod.literal("RefTagBlock"),
  "name": zod.string().describe('引用的节点名称')
})]))
}),zod.object({
  "type": zod.enum(['GENERATED']),
  "blocks": zod.array(zod.object({
  "id": zod.string().describe('Unique block ID'),
  "type": zod.enum(['text', 'markdown', 'code', 'tool_call', 'tool_result', 'image', 'reasoning']).describe('Message block types:\n- text: Plain text\n- markdown: Markdown content\n- code: Code block\n- tool_call: Tool call request\n- tool_result: Tool call result\n- image: Image (reserved for future)\n- reasoning: Reasoning content\n'),
  "content": zod.string().describe('Block content'),
  "metadata": zod.record(zod.string(), zod.unknown()).optional().describe('Additional metadata'),
  "toolCallId": zod.string().optional().describe('Tool call ID (for tool_call and tool_result types)'),
  "toolName": zod.string().optional().describe('Tool name (for tool_call type)'),
  "toolArgs": zod.unknown().optional().describe('Tool arguments (for tool_call type)'),
  "toolStatus": zod.enum(['pending', 'running', 'completed', 'error']).optional().describe('Tool call execution status')
})),
  "inputRef": zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
}),
  "promptRefs": zod.array(zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
})).optional(),
  "indirectPromptRefs": zod.array(zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
})).optional(),
  "inputVfsRef": zod.object({
  "nodeId": zod.uuid().describe('VFS 节点 ID'),
  "commit": zod.string().describe('VFS 状态的 commit hash')
}).nullish(),
  "outputVfsId": zod.uuid().nullish(),
  "postGenerationCommit": zod.string().nullish().describe('Post-generation commit hash - recorded after file modifications are complete')
}),zod.object({
  "type": zod.enum(['SANDBOX']),
  "entryFile": zod.string().default(getArtifactGraphResponseNodesItemContentFourEntryFileDefault)
}),zod.object({
  "type": zod.enum(['LOADER']),
  "mountpoints": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "path": zod.string().describe('挂载路径')
})).optional()
}),zod.object({
  "type": zod.enum(['STATE']),
  "name": zod.string().describe('状态节点的名称'),
  "description": zod.string().optional().describe('状态节点的描述')
}),zod.object({
  "type": zod.enum(['VFS']),
  "projectId": zod.string().describe('所属项目 ID'),
  "mounts": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "sourceNodeId": zod.uuid().describe('源 VFS 节点 ID'),
  "mountPath": zod.string().describe('挂载路径'),
  "sourceCommit": zod.string().optional().describe('源 VFS 版本 commit hash')
})).optional().describe('VfsMountConfig[] 挂载配置'),
  "fileCount": zod.number().optional().describe('文件总数'),
  "totalSize": zod.number().optional().describe('总大小 (bytes)'),
  "fileTree": zod.array(zod.object({
  "path": zod.string().describe('文件路径'),
  "size": zod.number().optional().describe('文件大小 (bytes)'),
  "mimeType": zod.string().optional().describe('MIME 类型')
})).optional().describe('文件目录树'),
  "files": zod.array(zod.object({
  "path": zod.string().describe('文件路径'),
  "size": zod.number().optional().describe('文件大小 (bytes)'),
  "mimeType": zod.string().optional().describe('MIME 类型')
})).optional().describe('文件列表（用于 API 验证）')
})]).optional()
})),
  "edges": zod.array(zod.object({
  "source": zod.uuid(),
  "target": zod.uuid(),
  "sourceHandle": zod.string().optional(),
  "targetHandle": zod.string().optional()
})),
  "version": zod.object({
  "id": zod.uuid(),
  "commitHash": zod.string(),
  "commitTags": zod.array(zod.string()).optional().describe('该版本上的所有标签'),
  "version": zod.string(),
  "entrypoint": zod.object({
  "saveCommit": zod.string().describe('Save 的 commit hash，指定启动时加载的存档'),
  "sandboxNodeId": zod.uuid().describe('沙箱节点 ID')
}).nullish(),
  "createdAt": zod.iso.datetime({})
})
})


/**
 * 设置指定 commit 上的 commitTags 列表（替换语义）。
如果某个 tag 已被同 artifact 的其他 commit 使用，则自动从旧 commit 上移除（override 语义）。
传空数组可清除该 commit 上的所有标签。

 * @summary 设置 commit 上的标签列表
 */
export const UpdateCommitTagsParams = zod.object({
  "artifactId": zod.uuid().describe('Artifact ID')
})

export const UpdateCommitTagsBody = zod.object({
  "commitHash": zod.string().describe('目标 commit hash'),
  "commitTags": zod.array(zod.string()).describe('要设置的标签列表。传空数组表示清除该 commit 上的所有标签。\n如果某个 tag 已被同 artifact 的其他 commit 使用，则自动从旧 commit 上移除。\n')
}).describe('设置指定 commit 上的标签列表（替换语义）')

export const UpdateCommitTagsResponse = zod.object({
  "message": zod.string(),
  "version": zod.object({
  "id": zod.uuid(),
  "version": zod.string(),
  "commitHash": zod.string().describe('SHA-256 前8位'),
  "commitTags": zod.array(zod.string()).optional().describe('该版本上的所有标签'),
  "changelog": zod.string().nullish(),
  "publishedAt": zod.iso.datetime({}).nullish(),
  "createdAt": zod.iso.datetime({})
})
})


/**
 * 将指定版本标记为 weak 版本（不可逆操作）。weak 版本不会对其关联的 node 产生引用计数。
标记为 weak 后，会尝试 GC 掉引用计数归零的 node 内容。
已经标记为 weak 的版本不能取消标记。

 * @summary 标记版本为 weak（不可逆）
 */
export const MarkVersionWeakParams = zod.object({
  "artifactId": zod.uuid().describe('Artifact ID'),
  "commitHash": zod.string().describe('版本的 commit hash')
})

export const MarkVersionWeakBody = zod.object({

}).describe('将一个 artifact 版本标记为 weak（不可逆操作）。\nweak 版本不对 node 产生引用计数，标记后尝试 GC 引用计数归零的 node 内容。\n')

export const MarkVersionWeakResponse = zod.object({
  "message": zod.string(),
  "gcResult": zod.object({
  "decremented": zod.number().optional().describe('引用计数被减少的内容数量'),
  "deleted": zod.number().optional().describe('引用计数归零被删除的内容数量')
})
})


/**
 * 获取所有公开的 Project，支持按 topic 过滤，支持排序
 * @summary 获取公开 Project 列表
 */
export const listProjectsQueryPageDefault = 1;

export const listProjectsQueryLimitDefault = 20;
export const listProjectsQueryLimitMax = 100;

export const listProjectsQuerySortByDefault = `createdAt`;export const listProjectsQuerySortOrderDefault = `desc`;

export const ListProjectsQueryParams = zod.object({
  "page": zod.number().min(1).default(listProjectsQueryPageDefault).describe('页码'),
  "limit": zod.number().min(1).max(listProjectsQueryLimitMax).default(listProjectsQueryLimitDefault).describe('每页数量'),
  "topic": zod.string().optional().describe('按 topic（hashtag）过滤'),
  "sortBy": zod.enum(['createdAt', 'updatedAt']).default(listProjectsQuerySortByDefault).describe('排序字段'),
  "sortOrder": zod.enum(['asc', 'desc']).default(listProjectsQuerySortOrderDefault).describe('排序方向')
})


export const listProjectsResponsePaginationLimitMax = 100;



export const ListProjectsResponse = zod.object({
  "projects": zod.array(zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "topic": zod.string().describe('Project 的 hashtag'),
  "description": zod.string().nullish(),
  "license": zod.string().nullish(),
  "coverUrls": zod.array(zod.url()).optional().describe('封面图片 URL 数组'),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({}),
  "owner": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "artifactCount": zod.number().optional().describe('关联 artifact 数量')
})),
  "pagination": zod.object({
  "page": zod.number().min(1),
  "limit": zod.number().min(1).max(listProjectsResponsePaginationLimitMax),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * 创建新的 Project，支持同时创建多个页面、关联多个 artifact 和定义角色。
metadata 字段中的 pages 数组可以包含多个页面配置，其中可以指定一个页面为主页。

 * @summary 创建 Project
 */
export const createProjectBodyNameMax = 100;

export const createProjectBodySlugMax = 100;


export const createProjectBodySlugRegExp = new RegExp('^[a-z0-9]+(-[a-z0-9]+)\*$');
export const createProjectBodyTopicMax = 100;

export const createProjectBodyIsListedDefault = true;export const createProjectBodyLicenseMax = 50;

export const createProjectBodyRolesItemNameMax = 50;


export const createProjectBodyPagesItemNameMax = 100;

export const createProjectBodyPagesItemIconMax = 50;

export const createProjectBodyHomepageIndexMin = 0;



export const CreateProjectBody = zod.object({
  "name": zod.string().min(1).max(createProjectBodyNameMax),
  "slug": zod.string().min(1).max(createProjectBodySlugMax).regex(createProjectBodySlugRegExp).describe('URL-friendly 标识符'),
  "topic": zod.string().min(1).max(createProjectBodyTopicMax).describe('Project 的 hashtag'),
  "description": zod.string().optional(),
  "isListed": zod.boolean().default(createProjectBodyIsListedDefault).describe('是否在公开列表中可见（可发现性）'),
  "license": zod.string().max(createProjectBodyLicenseMax).optional(),
  "coverUrls": zod.array(zod.url()).optional().describe('封面图片 URL 数组'),
  "artifacts": zod.array(zod.object({
  "artifactId": zod.uuid().describe('要关联的 Artifact ID'),
  "roleName": zod.string().describe('角色名称（必须是叶子角色）')
})).optional().describe('要关联的 artifact 列表（创建时 isOfficial 自动设为 true）'),
  "roles": zod.array(zod.object({
  "name": zod.string().min(1).max(createProjectBodyRolesItemNameMax).describe('角色名称，在同一 project 内必须唯一，同时作为角色标识符'),
  "description": zod.string().optional(),
  "parentName": zod.string().nullish().describe('父角色的名称')
})).min(1).describe('要创建的角色列表，角色名称必须唯一，支持树状结构，至少需要一个角色'),
  "pages": zod.array(zod.object({
  "name": zod.string().min(1).max(createProjectBodyPagesItemNameMax).describe('页面名称'),
  "icon": zod.string().max(createProjectBodyPagesItemIconMax).optional().describe('页面图标（emoji 或图标标识符）'),
  "content": zod.string().optional().describe('页面 HTML 内容')
})).optional().describe('要创建的页面列表'),
  "homepageIndex": zod.number().min(createProjectBodyHomepageIndexMin).optional().describe('首页在 pages 数组中的索引，不提供则不设置首页')
})


/**
 * 获取指定 Project 的详细信息。
访问权限由 ACL 系统控制，无权访问时返回 403。

 * @summary 获取 Project 详情
 */
export const GetProjectDetailParams = zod.object({
  "projectId": zod.uuid().describe('Project ID')
})

export const GetProjectDetailResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "slug": zod.string(),
  "topic": zod.string().describe('Project 的 hashtag'),
  "description": zod.string().nullish(),
  "license": zod.string().nullish(),
  "coverUrls": zod.array(zod.url()).optional().describe('封面图片 URL 数组'),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "isArchived": zod.boolean(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({}),
  "owner": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "artifacts": zod.array(zod.object({
  "artifact": zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "thumbnailUrl": zod.url().nullish(),
  "license": zod.string().nullish(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({}),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "tags": zod.array(zod.object({
  "slug": zod.string().describe('Tag slug (primary key)'),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "color": zod.string().nullish().describe('颜色代码 #RRGGBB')
})).optional(),
  "stats": zod.object({
  "viewCount": zod.number().optional().describe('浏览次数'),
  "favCount": zod.number().optional().describe('收藏次数'),
  "refCount": zod.number().optional().describe('引用次数（被 fork 次数）'),
  "downloadCount": zod.number().optional().describe('下载次数')
}).optional().describe('Artifact 统计信息')
}),
  "role": zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "parentRoleId": zod.uuid().nullish().describe('父角色 ID，用于构建角色树'),
  "isLeaf": zod.boolean().describe('是否为叶子角色，只有叶子角色可以分配给 artifact'),
  "createdAt": zod.iso.datetime({})
}).optional(),
  "isOfficial": zod.boolean().describe('是否为官方添加的 artifact'),
  "createdAt": zod.iso.datetime({}).describe('关联创建时间')
})).describe('关联的 artifact 列表'),
  "roles": zod.array(zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "parentRoleId": zod.uuid().nullish().describe('父角色 ID，用于构建角色树'),
  "isLeaf": zod.boolean().describe('是否为叶子角色，只有叶子角色可以分配给 artifact'),
  "createdAt": zod.iso.datetime({})
})).describe('Project 定义的角色列表'),
  "pages": zod.array(zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "icon": zod.string().nullish().describe('页面图标（emoji 或图标标识符）'),
  "order": zod.number().describe('显示顺序'),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})).describe('Project 页面列表（不含内容）'),
  "homepageId": zod.uuid().nullish().describe('主页 ID')
})


/**
 * 获取指定 Project 的特定页面详情，包括 HTML 内容。
访问权限由 ACL 系统控制，无权访问时返回 403。

 * @summary 获取 Project 页面详情
 */
export const GetProjectPageParams = zod.object({
  "projectId": zod.uuid().describe('Project ID'),
  "pageId": zod.uuid().describe('Page ID')
})

export const GetProjectPageResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "icon": zod.string().nullish().describe('页面图标（emoji 或图标标识符）'),
  "content": zod.string().nullish().describe('页面 HTML 内容'),
  "order": zod.number().describe('显示顺序'),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


/**
 * 获取指定 Project 关联的所有 Artifact，支持分页和过滤。
可选过滤条件：
- roleId: 按角色过滤，传 null 表示获取无角色的 artifacts
- isOfficial: 按是否官方过滤

 * @summary 获取 Project 的 Artifact 列表
 */
export const ListProjectArtifactsParams = zod.object({
  "projectId": zod.uuid().describe('Project ID')
})

export const listProjectArtifactsQueryPageDefault = 1;

export const listProjectArtifactsQueryLimitDefault = 20;
export const listProjectArtifactsQueryLimitMax = 100;

export const listProjectArtifactsQuerySortOrderDefault = `desc`;

export const ListProjectArtifactsQueryParams = zod.object({
  "page": zod.number().min(1).default(listProjectArtifactsQueryPageDefault).describe('页码'),
  "limit": zod.number().min(1).max(listProjectArtifactsQueryLimitMax).default(listProjectArtifactsQueryLimitDefault).describe('每页数量'),
  "roleId": zod.string().optional().describe('按角色 ID 过滤，传 \"null\" 字符串表示获取无角色的 artifacts'),
  "isOfficial": zod.boolean().optional().describe('按是否官方过滤'),
  "sortOrder": zod.enum(['asc', 'desc']).default(listProjectArtifactsQuerySortOrderDefault).describe('排序方向')
})


export const listProjectArtifactsResponsePaginationLimitMax = 100;



export const ListProjectArtifactsResponse = zod.object({
  "artifacts": zod.array(zod.object({
  "artifact": zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "thumbnailUrl": zod.url().nullish(),
  "license": zod.string().nullish(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({}),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "tags": zod.array(zod.object({
  "slug": zod.string().describe('Tag slug (primary key)'),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "color": zod.string().nullish().describe('颜色代码 #RRGGBB')
})).optional(),
  "stats": zod.object({
  "viewCount": zod.number().optional().describe('浏览次数'),
  "favCount": zod.number().optional().describe('收藏次数'),
  "refCount": zod.number().optional().describe('引用次数（被 fork 次数）'),
  "downloadCount": zod.number().optional().describe('下载次数')
}).optional().describe('Artifact 统计信息')
}),
  "role": zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "parentRoleId": zod.uuid().nullish().describe('父角色 ID，用于构建角色树'),
  "isLeaf": zod.boolean().describe('是否为叶子角色，只有叶子角色可以分配给 artifact'),
  "createdAt": zod.iso.datetime({})
}).optional(),
  "isOfficial": zod.boolean().describe('是否为官方添加的 artifact'),
  "createdAt": zod.iso.datetime({}).describe('关联创建时间')
})),
  "pagination": zod.object({
  "page": zod.number().min(1),
  "limit": zod.number().min(1).max(listProjectArtifactsResponsePaginationLimitMax),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * 将一个 Artifact 关联到指定的 Project。
- 必须指定角色（只能是叶子角色）
- 可选指定是否为官方 artifact（只有 owner 或 maintainer 可以设置为 true）

 * @summary 将 Artifact 链接到 Project
 */
export const LinkArtifactToProjectParams = zod.object({
  "projectId": zod.uuid().describe('Project ID')
})

export const linkArtifactToProjectBodyIsOfficialDefault = false;

export const LinkArtifactToProjectBody = zod.object({
  "artifactId": zod.uuid().describe('要关联的 Artifact ID'),
  "roleId": zod.uuid().describe('角色 ID（必须是叶子角色）'),
  "isOfficial": zod.boolean().default(linkArtifactToProjectBodyIsOfficialDefault).describe('是否为官方 artifact（只有 owner\/maintainer 可设置为 true）')
})


/**
 * 获取指定 Project 的所有动态，支持分页。
访问权限由 ACL 系统控制，无权访问时返回 403。

 * @summary 获取 Project 的动态列表
 */
export const ListProjectPostsParams = zod.object({
  "projectId": zod.uuid().describe('Project ID')
})

export const listProjectPostsQueryPageDefault = 1;

export const listProjectPostsQueryLimitDefault = 20;
export const listProjectPostsQueryLimitMax = 100;

export const listProjectPostsQuerySortByDefault = `createdAt`;export const listProjectPostsQuerySortOrderDefault = `desc`;

export const ListProjectPostsQueryParams = zod.object({
  "page": zod.number().min(1).default(listProjectPostsQueryPageDefault).describe('页码'),
  "limit": zod.number().min(1).max(listProjectPostsQueryLimitMax).default(listProjectPostsQueryLimitDefault).describe('每页数量'),
  "sortBy": zod.enum(['createdAt', 'updatedAt']).default(listProjectPostsQuerySortByDefault).describe('排序字段'),
  "sortOrder": zod.enum(['asc', 'desc']).default(listProjectPostsQuerySortOrderDefault).describe('排序方向')
})

export const listProjectPostsResponsePostsItemTitleMax = 200;


export const listProjectPostsResponsePaginationLimitMax = 100;



export const ListProjectPostsResponse = zod.object({
  "posts": zod.array(zod.object({
  "id": zod.uuid(),
  "projectId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "discussionId": zod.uuid().nullish(),
  "title": zod.string().max(listProjectPostsResponsePostsItemTitleMax),
  "content": zod.string().describe('HTML 内容'),
  "coverUrls": zod.array(zod.url()).nullish().describe('封面图片 URL 数组'),
  "isPinned": zod.boolean(),
  "replyCount": zod.number().optional().describe('关联讨论的回复数'),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})),
  "pagination": zod.object({
  "page": zod.number().min(1),
  "limit": zod.number().min(1).max(listProjectPostsResponsePaginationLimitMax),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * 在指定 Project 下创建新动态。需要认证。
需要对 Project 有写入权限。
创建动态时会同时创建一个关联的讨论。

 * @summary 创建动态
 */
export const CreateProjectPostParams = zod.object({
  "projectId": zod.uuid().describe('Project ID')
})

export const createProjectPostBodyTitleMax = 200;



export const CreateProjectPostBody = zod.object({
  "title": zod.string().min(1).max(createProjectPostBodyTitleMax),
  "content": zod.string().describe('HTML 内容'),
  "coverUrls": zod.array(zod.url()).optional().describe('封面图片 URL 数组')
})


/**
 * 获取指定动态的详细信息，包括关联的讨论。
访问权限由 ACL 系统控制，无权访问时返回 403。

 * @summary 获取动态详情
 */
export const GetProjectPostParams = zod.object({
  "projectId": zod.uuid().describe('Project ID'),
  "postId": zod.uuid().describe('Post ID')
})

export const getProjectPostResponseOneTitleMax = 200;

export const getProjectPostResponseTwoDiscussionOneTitleMax = 200;



export const GetProjectPostResponse = zod.object({
  "id": zod.uuid(),
  "projectId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "discussionId": zod.uuid().nullish(),
  "title": zod.string().max(getProjectPostResponseOneTitleMax),
  "content": zod.string().describe('HTML 内容'),
  "coverUrls": zod.array(zod.url()).nullish().describe('封面图片 URL 数组'),
  "isPinned": zod.boolean(),
  "replyCount": zod.number().optional().describe('关联讨论的回复数'),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}).and(zod.object({
  "discussion": zod.object({
  "id": zod.uuid(),
  "targetType": zod.enum(['ARTIFACT', 'PROJECT', 'POST']).describe('讨论可以关联到的目标类型'),
  "targetId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().optional(),
  "avatarUrl": zod.url().optional()
}),
  "title": zod.string().max(getProjectPostResponseTwoDiscussionOneTitleMax).optional(),
  "content": zod.string(),
  "category": zod.enum(['QUESTION', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'GENERAL']).describe('讨论分类'),
  "isPinned": zod.boolean(),
  "isLocked": zod.boolean(),
  "replyCount": zod.number(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}).nullish()
}))


/**
 * 更新指定动态的信息。需要认证。
- 动态作者可以更新标题、内容、封面图片
- owner 和 maintainer 可以额外设置是否置顶

 * @summary 更新动态
 */
export const UpdateProjectPostParams = zod.object({
  "projectId": zod.uuid().describe('Project ID'),
  "postId": zod.uuid().describe('Post ID')
})

export const updateProjectPostBodyTitleMax = 200;



export const UpdateProjectPostBody = zod.object({
  "title": zod.string().min(1).max(updateProjectPostBodyTitleMax).optional(),
  "content": zod.string().optional().describe('HTML 内容'),
  "coverUrls": zod.array(zod.url()).optional().describe('封面图片 URL 数组'),
  "isPinned": zod.boolean().optional().describe('是否置顶（仅 owner 和 maintainer 可设置）')
})

export const updateProjectPostResponsePostOneTitleMax = 200;

export const updateProjectPostResponsePostTwoDiscussionOneTitleMax = 200;



export const UpdateProjectPostResponse = zod.object({
  "message": zod.string(),
  "post": zod.object({
  "id": zod.uuid(),
  "projectId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "discussionId": zod.uuid().nullish(),
  "title": zod.string().max(updateProjectPostResponsePostOneTitleMax),
  "content": zod.string().describe('HTML 内容'),
  "coverUrls": zod.array(zod.url()).nullish().describe('封面图片 URL 数组'),
  "isPinned": zod.boolean(),
  "replyCount": zod.number().optional().describe('关联讨论的回复数'),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}).and(zod.object({
  "discussion": zod.object({
  "id": zod.uuid(),
  "targetType": zod.enum(['ARTIFACT', 'PROJECT', 'POST']).describe('讨论可以关联到的目标类型'),
  "targetId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().optional(),
  "avatarUrl": zod.url().optional()
}),
  "title": zod.string().max(updateProjectPostResponsePostTwoDiscussionOneTitleMax).optional(),
  "content": zod.string(),
  "category": zod.enum(['QUESTION', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'GENERAL']).describe('讨论分类'),
  "isPinned": zod.boolean(),
  "isLocked": zod.boolean(),
  "replyCount": zod.number(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}).nullish()
}))
})


/**
 * 删除指定的动态。需要认证。
仅动态作者、project owner 或 maintainer 可以删除。
删除动态时会同时删除关联的讨论。

 * @summary 删除动态
 */
export const DeleteProjectPostParams = zod.object({
  "projectId": zod.uuid().describe('Project ID'),
  "postId": zod.uuid().describe('Post ID')
})

export const DeleteProjectPostResponse = zod.object({
  "message": zod.string()
})


/**
 * 获取指定目标（Artifact 或 Project）的讨论列表。
必须指定 targetType 和 targetId。

 * @summary 获取讨论列表
 */
export const listDiscussionsQueryPageDefault = 1;

export const listDiscussionsQueryLimitDefault = 20;
export const listDiscussionsQueryLimitMax = 100;

export const listDiscussionsQuerySortByDefault = `createdAt`;export const listDiscussionsQuerySortOrderDefault = `desc`;

export const ListDiscussionsQueryParams = zod.object({
  "targetType": zod.enum(['ARTIFACT', 'PROJECT', 'POST']).describe('目标类型'),
  "targetId": zod.uuid().describe('目标 ID'),
  "category": zod.enum(['QUESTION', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'GENERAL']).optional().describe('按分类筛选'),
  "page": zod.number().min(1).default(listDiscussionsQueryPageDefault).describe('页码'),
  "limit": zod.number().min(1).max(listDiscussionsQueryLimitMax).default(listDiscussionsQueryLimitDefault).describe('每页数量'),
  "sortBy": zod.enum(['createdAt', 'updatedAt', 'replyCount']).default(listDiscussionsQuerySortByDefault).describe('排序字段'),
  "sortOrder": zod.enum(['asc', 'desc']).default(listDiscussionsQuerySortOrderDefault).describe('排序方向')
})

export const listDiscussionsResponseDiscussionsItemTitleMax = 200;


export const listDiscussionsResponsePaginationLimitMax = 100;



export const ListDiscussionsResponse = zod.object({
  "discussions": zod.array(zod.object({
  "id": zod.uuid(),
  "targetType": zod.enum(['ARTIFACT', 'PROJECT', 'POST']).describe('讨论可以关联到的目标类型'),
  "targetId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().optional(),
  "avatarUrl": zod.url().optional()
}),
  "title": zod.string().max(listDiscussionsResponseDiscussionsItemTitleMax).optional(),
  "content": zod.string(),
  "category": zod.enum(['QUESTION', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'GENERAL']).describe('讨论分类'),
  "isPinned": zod.boolean(),
  "isLocked": zod.boolean(),
  "replyCount": zod.number(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})),
  "pagination": zod.object({
  "page": zod.number().min(1),
  "limit": zod.number().min(1).max(listDiscussionsResponsePaginationLimitMax),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * 在指定目标上创建新讨论。需要认证。

 * @summary 创建讨论
 */
export const CreateDiscussionQueryParams = zod.object({
  "targetType": zod.enum(['ARTIFACT', 'PROJECT', 'POST']).describe('目标类型'),
  "targetId": zod.uuid().describe('目标 ID')
})

export const createDiscussionBodyTitleMax = 200;




export const CreateDiscussionBody = zod.object({
  "title": zod.string().max(createDiscussionBodyTitleMax).optional(),
  "content": zod.string().min(1),
  "category": zod.enum(['QUESTION', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'GENERAL']).optional().describe('讨论分类')
})


/**
 * @summary 获取讨论详情
 */
export const GetDiscussionParams = zod.object({
  "discussionId": zod.uuid().describe('讨论 ID')
})

export const getDiscussionResponseOneTitleMax = 200;



export const GetDiscussionResponse = zod.object({
  "id": zod.uuid(),
  "targetType": zod.enum(['ARTIFACT', 'PROJECT', 'POST']).describe('讨论可以关联到的目标类型'),
  "targetId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().optional(),
  "avatarUrl": zod.url().optional()
}),
  "title": zod.string().max(getDiscussionResponseOneTitleMax).optional(),
  "content": zod.string(),
  "category": zod.enum(['QUESTION', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'GENERAL']).describe('讨论分类'),
  "isPinned": zod.boolean(),
  "isLocked": zod.boolean(),
  "replyCount": zod.number(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


/**
 * 更新讨论内容。只有作者可以更新。
 * @summary 更新讨论
 */
export const UpdateDiscussionParams = zod.object({
  "discussionId": zod.uuid().describe('讨论 ID')
})

export const updateDiscussionBodyTitleMax = 200;




export const UpdateDiscussionBody = zod.object({
  "title": zod.string().max(updateDiscussionBodyTitleMax).optional(),
  "content": zod.string().min(1).optional(),
  "category": zod.enum(['QUESTION', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'GENERAL']).optional().describe('讨论分类')
})

export const updateDiscussionResponseDiscussionOneTitleMax = 200;



export const UpdateDiscussionResponse = zod.object({
  "message": zod.string(),
  "discussion": zod.object({
  "id": zod.uuid(),
  "targetType": zod.enum(['ARTIFACT', 'PROJECT', 'POST']).describe('讨论可以关联到的目标类型'),
  "targetId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().optional(),
  "avatarUrl": zod.url().optional()
}),
  "title": zod.string().max(updateDiscussionResponseDiscussionOneTitleMax).optional(),
  "content": zod.string(),
  "category": zod.enum(['QUESTION', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'GENERAL']).describe('讨论分类'),
  "isPinned": zod.boolean(),
  "isLocked": zod.boolean(),
  "replyCount": zod.number(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})
})


/**
 * 删除讨论。作者或管理员可以删除。
 * @summary 删除讨论
 */
export const DeleteDiscussionParams = zod.object({
  "discussionId": zod.uuid().describe('讨论 ID')
})

export const DeleteDiscussionResponse = zod.object({
  "message": zod.string()
})


/**
 * 管理员功能。
 * @summary 置顶/取消置顶讨论
 */
export const PinDiscussionParams = zod.object({
  "discussionId": zod.uuid().describe('讨论 ID')
})

export const PinDiscussionBody = zod.object({
  "isPinned": zod.boolean()
})

export const pinDiscussionResponseDiscussionOneTitleMax = 200;



export const PinDiscussionResponse = zod.object({
  "message": zod.string(),
  "discussion": zod.object({
  "id": zod.uuid(),
  "targetType": zod.enum(['ARTIFACT', 'PROJECT', 'POST']).describe('讨论可以关联到的目标类型'),
  "targetId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().optional(),
  "avatarUrl": zod.url().optional()
}),
  "title": zod.string().max(pinDiscussionResponseDiscussionOneTitleMax).optional(),
  "content": zod.string(),
  "category": zod.enum(['QUESTION', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'GENERAL']).describe('讨论分类'),
  "isPinned": zod.boolean(),
  "isLocked": zod.boolean(),
  "replyCount": zod.number(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})
})


/**
 * 管理员功能。锁定后不能发表新回复。
 * @summary 锁定/解锁讨论
 */
export const LockDiscussionParams = zod.object({
  "discussionId": zod.uuid().describe('讨论 ID')
})

export const LockDiscussionBody = zod.object({
  "isLocked": zod.boolean()
})

export const lockDiscussionResponseDiscussionOneTitleMax = 200;



export const LockDiscussionResponse = zod.object({
  "message": zod.string(),
  "discussion": zod.object({
  "id": zod.uuid(),
  "targetType": zod.enum(['ARTIFACT', 'PROJECT', 'POST']).describe('讨论可以关联到的目标类型'),
  "targetId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().optional(),
  "avatarUrl": zod.url().optional()
}),
  "title": zod.string().max(lockDiscussionResponseDiscussionOneTitleMax).optional(),
  "content": zod.string(),
  "category": zod.enum(['QUESTION', 'FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'GENERAL']).describe('讨论分类'),
  "isPinned": zod.boolean(),
  "isLocked": zod.boolean(),
  "replyCount": zod.number(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})
})


/**
 * @summary 获取讨论回复列表
 */
export const ListDiscussionRepliesParams = zod.object({
  "discussionId": zod.uuid().describe('讨论 ID')
})

export const listDiscussionRepliesQueryPageDefault = 1;

export const listDiscussionRepliesQueryLimitDefault = 50;
export const listDiscussionRepliesQueryLimitMax = 100;

export const listDiscussionRepliesQuerySortOrderDefault = `asc`;

export const ListDiscussionRepliesQueryParams = zod.object({
  "page": zod.number().min(1).default(listDiscussionRepliesQueryPageDefault).describe('页码'),
  "limit": zod.number().min(1).max(listDiscussionRepliesQueryLimitMax).default(listDiscussionRepliesQueryLimitDefault).describe('每页数量'),
  "sortOrder": zod.enum(['asc', 'desc']).default(listDiscussionRepliesQuerySortOrderDefault).describe('排序方向')
})


export const listDiscussionRepliesResponsePaginationLimitMax = 100;



export const ListDiscussionRepliesResponse = zod.object({
  "replies": zod.array(zod.object({
  "id": zod.uuid(),
  "discussionId": zod.uuid(),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().optional(),
  "avatarUrl": zod.url().optional()
}),
  "parentReplyId": zod.uuid().optional().describe('父回复 ID，用于嵌套回复'),
  "content": zod.string(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})),
  "pagination": zod.object({
  "page": zod.number().min(1),
  "limit": zod.number().min(1).max(listDiscussionRepliesResponsePaginationLimitMax),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * 在讨论中发表回复。需要认证。
 * @summary 创建回复
 */
export const CreateDiscussionReplyParams = zod.object({
  "discussionId": zod.uuid().describe('讨论 ID')
})




export const CreateDiscussionReplyBody = zod.object({
  "content": zod.string().min(1),
  "parentReplyId": zod.uuid().optional().describe('父回复 ID，用于嵌套回复')
})


/**
 * 删除回复。作者或管理员可以删除。
 * @summary 删除回复
 */
export const DeleteDiscussionReplyParams = zod.object({
  "replyId": zod.uuid().describe('回复 ID')
})

export const DeleteDiscussionReplyResponse = zod.object({
  "message": zod.string()
})


/**
 * 获取文章详情，包括内容和元数据。
返回值中包含 artifactId（通过 sandboxNodeId 获取）。

 * @summary 获取文章详情
 */
export const GetArticleParams = zod.object({
  "articleId": zod.uuid()
})

export const GetArticleResponse = zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "content": zod.array(zod.union([zod.object({
  "type": zod.enum(['text']),
  "id": zod.string().describe('文本块唯一标识符'),
  "text": zod.string().describe('文本内容（支持 markdown heading）')
}),zod.object({
  "type": zod.enum(['game_ref']),
  "textId": zod.string().describe('关联的文本块 ID'),
  "saveCommit": zod.string().describe('Save 版本 commit hash（可唯一索引到对应的 save node version）')
})])),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "artifactId": zod.uuid().describe('Artifact ID'),
  "artifactCommit": zod.string().describe('Artifact 版本 commit hash'),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "likes": zod.number(),
  "collections": zod.number(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


/**
 * 创建或更新文章（upsert 语义）。
- 如果 articleId 不存在，创建新文章
- 如果 articleId 存在且 author 是当前用户，更新文章
- 如果 articleId 存在但 author 不是当前用户，返回 403

 * @summary 创建或更新文章
 */
export const UpsertArticleParams = zod.object({
  "articleId": zod.uuid()
})

export const upsertArticleBodyTitleMax = 200;

export const upsertArticleBodyIsListedDefault = false;

export const UpsertArticleBody = zod.object({
  "title": zod.string().min(1).max(upsertArticleBodyTitleMax),
  "artifactId": zod.uuid().describe('Artifact ID'),
  "artifactCommit": zod.string().describe('Artifact 版本 commit hash'),
  "content": zod.array(zod.union([zod.object({
  "type": zod.enum(['text']),
  "id": zod.string().describe('文本块唯一标识符'),
  "text": zod.string().describe('文本内容（支持 markdown heading）')
}),zod.object({
  "type": zod.enum(['game_ref']),
  "textId": zod.string().describe('关联的文本块 ID'),
  "saveCommit": zod.string().describe('Save 版本 commit hash（可唯一索引到对应的 save node version）')
})])),
  "isListed": zod.boolean().default(upsertArticleBodyIsListedDefault).describe('是否在公开列表中可见（可发现性）')
})

export const UpsertArticleResponse = zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "content": zod.array(zod.union([zod.object({
  "type": zod.enum(['text']),
  "id": zod.string().describe('文本块唯一标识符'),
  "text": zod.string().describe('文本内容（支持 markdown heading）')
}),zod.object({
  "type": zod.enum(['game_ref']),
  "textId": zod.string().describe('关联的文本块 ID'),
  "saveCommit": zod.string().describe('Save 版本 commit hash（可唯一索引到对应的 save node version）')
})])),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "artifactId": zod.uuid().describe('Artifact ID'),
  "artifactCommit": zod.string().describe('Artifact 版本 commit hash'),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "likes": zod.number(),
  "collections": zod.number(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


/**
 * 获取与指定 artifact 关联的所有公开文章，支持分页。

 * @summary 获取与 artifact 关联的文章列表
 */
export const ListArticlesByArtifactParams = zod.object({
  "artifactId": zod.uuid().describe('Artifact ID')
})

export const listArticlesByArtifactQueryPageDefault = 1;

export const listArticlesByArtifactQueryLimitDefault = 20;
export const listArticlesByArtifactQueryLimitMax = 100;



export const ListArticlesByArtifactQueryParams = zod.object({
  "page": zod.number().min(1).default(listArticlesByArtifactQueryPageDefault).describe('页码（从1开始）'),
  "limit": zod.number().min(1).max(listArticlesByArtifactQueryLimitMax).default(listArticlesByArtifactQueryLimitDefault).describe('每页数量')
})


export const listArticlesByArtifactResponsePaginationLimitMax = 100;



export const ListArticlesByArtifactResponse = zod.object({
  "articles": zod.array(zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "content": zod.array(zod.union([zod.object({
  "type": zod.enum(['text']),
  "id": zod.string().describe('文本块唯一标识符'),
  "text": zod.string().describe('文本内容（支持 markdown heading）')
}),zod.object({
  "type": zod.enum(['game_ref']),
  "textId": zod.string().describe('关联的文本块 ID'),
  "saveCommit": zod.string().describe('Save 版本 commit hash（可唯一索引到对应的 save node version）')
})])),
  "author": zod.object({
  "id": zod.uuid(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "avatarUrl": zod.url().nullish()
}),
  "artifactId": zod.uuid().describe('Artifact ID'),
  "artifactCommit": zod.string().describe('Artifact 版本 commit hash'),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "likes": zod.number(),
  "collections": zod.number(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})),
  "pagination": zod.object({
  "page": zod.number().min(1),
  "limit": zod.number().min(1).max(listArticlesByArtifactResponsePaginationLimitMax),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * 创建一个新的存档。使用 multipart/form-data 上传元数据和 quads.bin 二进制文件。
元数据通过 JSON 字符串的 `metadata` 字段传递，二进制数据通过 `data` 字段传递。

 * @summary 创建存档
 */
export const createSaveBodyMetadataIsListedDefault = false;

export const CreateSaveBody = zod.object({
  "metadata": zod.object({
  "stateNodeId": zod.uuid().describe('关联的 STATE 节点 ID'),
  "stateNodeCommit": zod.string().describe('关联的 STATE 节点版本 commit hash'),
  "commit": zod.string().describe('Save 版本 commit hash（客户端计算）'),
  "parent": zod.string().nullish().describe('父版本 commit hash（可选）'),
  "sourceArtifactId": zod.uuid().describe('关联的 artifact ID'),
  "sourceArtifactCommit": zod.string().describe('关联的 artifact 版本 commit hash'),
  "contentHash": zod.string().describe('内容指纹'),
  "title": zod.string().optional().describe('存档标题'),
  "description": zod.string().optional().describe('存档描述'),
  "isListed": zod.boolean().default(createSaveBodyMetadataIsListedDefault).describe('是否在公开列表中可见（可发现性）')
}),
  "data": zod.instanceof(File)
})


/**
 * 查询存档列表，支持两种查询方式（二选一）：
1. 按 STATE 节点版本查询：同时提供 stateNodeId + stateNodeCommit
2. 按 Save 节点 ID 查询：提供 saveId

两组参数必须提供其中一组，不能同时提供或都不提供。

 * @summary 获取存档列表
 */
export const listSavesQueryPageDefault = 1;

export const listSavesQueryLimitDefault = 20;
export const listSavesQueryLimitMax = 100;



export const ListSavesQueryParams = zod.object({
  "stateNodeId": zod.uuid().optional().describe('STATE 节点 ID（与 stateNodeCommit 一起使用）'),
  "stateNodeCommit": zod.string().optional().describe('STATE 节点的 commit hash（与 stateNodeId 一起使用）'),
  "saveId": zod.uuid().optional().describe('Save 节点 ID（单独使用，与 stateNodeId\/stateNodeCommit 互斥）'),
  "author": zod.uuid().optional().describe('按作者 ID 过滤'),
  "page": zod.number().min(1).default(listSavesQueryPageDefault).describe('页码（从1开始）'),
  "limit": zod.number().min(1).max(listSavesQueryLimitMax).default(listSavesQueryLimitDefault).describe('每页数量')
})


export const listSavesResponsePaginationLimitMax = 100;



export const ListSavesResponse = zod.object({
  "saves": zod.array(zod.object({
  "saveId": zod.string().describe('Save 节点 ID（服务端计算：hash(stateNodeId, stateNodeCommit, userId, sourceArtifactId, sourceArtifactCommit)）'),
  "commit": zod.string().describe('Save 版本 commit hash'),
  "parent": zod.string().nullish().describe('父版本 commit hash'),
  "authorId": zod.uuid(),
  "authoredAt": zod.iso.datetime({}),
  "stateNodeId": zod.uuid().describe('关联的 STATE 节点 ID'),
  "stateNodeCommit": zod.string().describe('关联的 STATE 节点版本 commit hash'),
  "sourceArtifactId": zod.uuid().describe('创建此 Save 的 artifact ID'),
  "sourceArtifactCommit": zod.string().describe('创建此 Save 的 artifact 版本 commit hash'),
  "title": zod.string().nullish(),
  "description": zod.string().nullish(),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "createdAt": zod.iso.datetime({})
})),
  "pagination": zod.object({
  "page": zod.number().min(1),
  "limit": zod.number().min(1).max(listSavesResponsePaginationLimitMax),
  "total": zod.number(),
  "totalPages": zod.number()
})
})


/**
 * 通过 commit hash 获取指定存档的详细信息。commit 是全局唯一的。

 * @summary 获取存档详情
 */
export const GetSaveParams = zod.object({
  "commit": zod.string()
})

export const GetSaveResponse = zod.object({
  "saveId": zod.string().describe('Save 节点 ID（服务端计算：hash(stateNodeId, stateNodeCommit, userId, sourceArtifactId, sourceArtifactCommit)）'),
  "commit": zod.string().describe('Save 版本 commit hash'),
  "parent": zod.string().nullish().describe('父版本 commit hash'),
  "authorId": zod.uuid(),
  "authoredAt": zod.iso.datetime({}),
  "stateNodeId": zod.uuid().describe('关联的 STATE 节点 ID'),
  "stateNodeCommit": zod.string().describe('关联的 STATE 节点版本 commit hash'),
  "sourceArtifactId": zod.uuid().describe('创建此 Save 的 artifact ID'),
  "sourceArtifactCommit": zod.string().describe('创建此 Save 的 artifact 版本 commit hash'),
  "title": zod.string().nullish(),
  "description": zod.string().nullish(),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）'),
  "createdAt": zod.iso.datetime({})
})


/**
 * 通过 commit hash 删除指定存档。仅作者可执行此操作。
同时清理 R2 中的 quads.bin 二进制数据。

 * @summary 删除存档
 */
export const DeleteSaveParams = zod.object({
  "commit": zod.string()
})


/**
 * 通过 commit hash 下载存档的 quads.bin 二进制数据。

 * @summary 下载存档数据
 */
export const GetSaveDataParams = zod.object({
  "commit": zod.string()
})


/**
 * Returns versions for a node, ordered by authored_at descending. Supports cursor-based pagination.
 * @summary Get versions for a node
 */
export const GetNodeVersionsParams = zod.object({
  "nodeId": zod.string().describe('Node UUID')
})

export const getNodeVersionsQueryLimitDefault = 20;
export const getNodeVersionsQueryLimitMax = 100;



export const GetNodeVersionsQueryParams = zod.object({
  "cursor": zod.string().optional().describe('Pagination cursor (nextCursor from previous response)'),
  "limit": zod.number().min(1).max(getNodeVersionsQueryLimitMax).default(getNodeVersionsQueryLimitDefault).describe('Number of versions per page')
})

export const GetNodeVersionsResponse = zod.object({
  "versions": zod.array(zod.object({
  "nodeId": zod.string().describe('Node UUID (globally unique, cross-artifact persistent)'),
  "commit": zod.string().describe('Version hash (SHA-256 first 40 chars)'),
  "parent": zod.string().nullish().describe('Parent commit hash (null for root version)'),
  "authorId": zod.string().describe('Author user ID'),
  "authoredAt": zod.iso.datetime({}).describe('Version creation timestamp'),
  "type": zod.enum(['PROMPT', 'INPUT', 'GENERATED', 'VFS', 'STATE', 'LOADER', 'SANDBOX', 'SAVE']).describe('Node type (including SAVE for save nodes)'),
  "name": zod.string().nullish(),
  "contentHash": zod.string().describe('Content fingerprint (determines which content table to query)'),
  "message": zod.string().nullish().describe('Commit message'),
  "tag": zod.string().nullish().describe('Semver tag (e.g. v1.0.0)'),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）')
})),
  "nextCursor": zod.string().nullish().describe('Cursor for the next page, null if no more data')
})


/**
 * Returns the full version detail including content from the typed content table.
commit 是全局唯一主键，无需额外的 nodeId。

 * @summary Get a specific version detail
 */
export const GetNodeVersionParams = zod.object({
  "commit": zod.string().describe('Version commit hash')
})

export const getNodeVersionResponseTwoContentOneGenerationConfigTemperatureMin = 0;
export const getNodeVersionResponseTwoContentOneGenerationConfigTemperatureMax = 2;

export const getNodeVersionResponseTwoContentFourEntryFileDefault = `index.html`;

export const GetNodeVersionResponse = zod.object({
  "nodeId": zod.string().describe('Node UUID (globally unique, cross-artifact persistent)'),
  "commit": zod.string().describe('Version hash (SHA-256 first 40 chars)'),
  "parent": zod.string().nullish().describe('Parent commit hash (null for root version)'),
  "authorId": zod.string().describe('Author user ID'),
  "authoredAt": zod.iso.datetime({}).describe('Version creation timestamp'),
  "type": zod.enum(['PROMPT', 'INPUT', 'GENERATED', 'VFS', 'STATE', 'LOADER', 'SANDBOX', 'SAVE']).describe('Node type (including SAVE for save nodes)'),
  "name": zod.string().nullish(),
  "contentHash": zod.string().describe('Content fingerprint (determines which content table to query)'),
  "message": zod.string().nullish().describe('Commit message'),
  "tag": zod.string().nullish().describe('Semver tag (e.g. v1.0.0)'),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）')
}).and(zod.object({
  "content": zod.union([zod.object({
  "type": zod.enum(['INPUT']),
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("TextBlock"),
  "value": zod.string()
}),zod.object({
  "type": zod.literal("RefTagBlock"),
  "name": zod.string().describe('引用的节点名称')
})])),
  "mountpoints": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "path": zod.string().describe('挂载路径')
})).optional(),
  "generationConfig": zod.object({
  "model": zod.string().optional().describe('生成使用的模型（空=使用全局设置）'),
  "temperature": zod.number().min(getNodeVersionResponseTwoContentOneGenerationConfigTemperatureMin).max(getNodeVersionResponseTwoContentOneGenerationConfigTemperatureMax).optional().describe('生成温度'),
  "schema": zod.string().optional().describe('结构化输出的 JSON Schema')
}).optional()
}),zod.object({
  "type": zod.enum(['PROMPT']),
  "blocks": zod.array(zod.union([zod.object({
  "type": zod.literal("TextBlock"),
  "value": zod.string()
}),zod.object({
  "type": zod.literal("RefTagBlock"),
  "name": zod.string().describe('引用的节点名称')
})]))
}),zod.object({
  "type": zod.enum(['GENERATED']),
  "blocks": zod.array(zod.object({
  "id": zod.string().describe('Unique block ID'),
  "type": zod.enum(['text', 'markdown', 'code', 'tool_call', 'tool_result', 'image', 'reasoning']).describe('Message block types:\n- text: Plain text\n- markdown: Markdown content\n- code: Code block\n- tool_call: Tool call request\n- tool_result: Tool call result\n- image: Image (reserved for future)\n- reasoning: Reasoning content\n'),
  "content": zod.string().describe('Block content'),
  "metadata": zod.record(zod.string(), zod.unknown()).optional().describe('Additional metadata'),
  "toolCallId": zod.string().optional().describe('Tool call ID (for tool_call and tool_result types)'),
  "toolName": zod.string().optional().describe('Tool name (for tool_call type)'),
  "toolArgs": zod.unknown().optional().describe('Tool arguments (for tool_call type)'),
  "toolStatus": zod.enum(['pending', 'running', 'completed', 'error']).optional().describe('Tool call execution status')
})),
  "inputRef": zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
}),
  "promptRefs": zod.array(zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
})).optional(),
  "indirectPromptRefs": zod.array(zod.object({
  "id": zod.uuid().describe('节点 ID'),
  "commit": zod.string().describe('引用时的 commit hash')
})).optional(),
  "inputVfsRef": zod.object({
  "nodeId": zod.uuid().describe('VFS 节点 ID'),
  "commit": zod.string().describe('VFS 状态的 commit hash')
}).nullish(),
  "outputVfsId": zod.uuid().nullish(),
  "postGenerationCommit": zod.string().nullish().describe('Post-generation commit hash - recorded after file modifications are complete')
}),zod.object({
  "type": zod.enum(['SANDBOX']),
  "entryFile": zod.string().default(getNodeVersionResponseTwoContentFourEntryFileDefault)
}),zod.object({
  "type": zod.enum(['LOADER']),
  "mountpoints": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "path": zod.string().describe('挂载路径')
})).optional()
}),zod.object({
  "type": zod.enum(['STATE']),
  "name": zod.string().describe('状态节点的名称'),
  "description": zod.string().optional().describe('状态节点的描述')
}),zod.object({
  "type": zod.enum(['VFS']),
  "projectId": zod.string().describe('所属项目 ID'),
  "mounts": zod.array(zod.object({
  "id": zod.string().describe('挂载点唯一标识符'),
  "sourceNodeId": zod.uuid().describe('源 VFS 节点 ID'),
  "mountPath": zod.string().describe('挂载路径'),
  "sourceCommit": zod.string().optional().describe('源 VFS 版本 commit hash')
})).optional().describe('VfsMountConfig[] 挂载配置'),
  "fileCount": zod.number().optional().describe('文件总数'),
  "totalSize": zod.number().optional().describe('总大小 (bytes)'),
  "fileTree": zod.array(zod.object({
  "path": zod.string().describe('文件路径'),
  "size": zod.number().optional().describe('文件大小 (bytes)'),
  "mimeType": zod.string().optional().describe('MIME 类型')
})).optional().describe('文件目录树'),
  "files": zod.array(zod.object({
  "path": zod.string().describe('文件路径'),
  "size": zod.number().optional().describe('文件大小 (bytes)'),
  "mimeType": zod.string().optional().describe('MIME 类型')
})).optional().describe('文件列表（用于 API 验证）')
})]).optional(),
  "refs": zod.array(zod.object({
  "targetNodeId": zod.string(),
  "targetCommit": zod.string(),
  "refType": zod.enum(['input', 'prompt', 'indirect_prompt', 'input_vfs', 'output_vfs']).describe('Type of reference between node versions (lineage tracking).\n- input: GENERATED\'s trigger input (INPUT node version)\n- prompt: GENERATED\'s direct prompt reference (PROMPT node version)\n- indirect_prompt: GENERATED\'s indirect prompt reference\n- input_vfs: Pre-generation VFS snapshot reference\n- output_vfs: Post-generation associated VFS node version\n')
})).optional().describe('Lineage references (for GENERATED nodes)')
}))


/**
 * Returns versions whose parent is the given commit.
commit 是全局唯一主键，无需额外的 nodeId。

 * @summary Get child versions
 */
export const GetNodeVersionChildrenParams = zod.object({
  "commit": zod.string().describe('Parent commit hash')
})

export const GetNodeVersionChildrenResponse = zod.object({
  "versions": zod.array(zod.object({
  "nodeId": zod.string().describe('Node UUID (globally unique, cross-artifact persistent)'),
  "commit": zod.string().describe('Version hash (SHA-256 first 40 chars)'),
  "parent": zod.string().nullish().describe('Parent commit hash (null for root version)'),
  "authorId": zod.string().describe('Author user ID'),
  "authoredAt": zod.iso.datetime({}).describe('Version creation timestamp'),
  "type": zod.enum(['PROMPT', 'INPUT', 'GENERATED', 'VFS', 'STATE', 'LOADER', 'SANDBOX', 'SAVE']).describe('Node type (including SAVE for save nodes)'),
  "name": zod.string().nullish(),
  "contentHash": zod.string().describe('Content fingerprint (determines which content table to query)'),
  "message": zod.string().nullish().describe('Commit message'),
  "tag": zod.string().nullish().describe('Semver tag (e.g. v1.0.0)'),
  "isListed": zod.boolean().describe('是否在公开列表中可见（可发现性）')
}))
})


/**
 * 下载指定版本的 tar.gz 归档文件（VFS 节点的二进制内容）。
commit 是全局唯一主键，无需额外的 nodeId。

 * @summary 下载节点版本的 VFS 归档文件
 */
export const GetNodeVersionArchiveParams = zod.object({
  "commit": zod.string().describe('节点版本 commit hash')
})
