/**
 * usePub — Type-safe backend service proxy.
 *
 * Returns a two-level proxy where services are accessed as:
 *   pub.namespace.ServiceName(inputs)
 *
 * The proxy maps `pub.ns.Name(inputs)` to
 * `client.getService('ns:Name').call(inputs)`.
 *
 * Type safety comes from ServiceMap declaration merging
 * (auto-generated by docs codegen into /lib/game-sdk/generated/services.d.ts).
 */

import { useMemo, useRef } from 'react'
import { initSandboxClient, type ISandboxClient, type ServiceMap } from '@pubwiki/sandbox-client'

// ── Type helpers ──────────────────────────────────────────────────────────

/** A callable service: invoke directly for call, or use .stream() for streaming. */
export interface ServiceCallable<
  TInputs = Record<string, unknown>,
  TOutputs = Record<string, unknown>
> {
  (inputs?: TInputs): Promise<TOutputs>
  stream(inputs: TInputs, on: (value: TOutputs) => void): Promise<void>
}

/** Extract namespace portion from 'ns:Name' keys */
type ServiceNS<K> = K extends `${infer NS}:${string}` ? NS : never

/** Build nested proxy type: { namespace: { ServiceName: ServiceCallable } } */
type PubProxyMap = {
  [NS in ServiceNS<keyof ServiceMap>]: {
    [K in keyof ServiceMap as K extends `${NS}:${infer Name}` ? Name : never]:
      ServiceMap[K] extends { inputs: infer I; outputs: infer O }
        ? ServiceCallable<I, O>
        : ServiceCallable
  }
}

/** When ServiceMap is empty (no codegen yet), fall back to untyped access. */
export type PubBackend = [keyof ServiceMap] extends [never]
  ? Record<string, Record<string, ServiceCallable>>
  : PubProxyMap

// ── Proxy internals ──────────────────────────────────────────────────────

/** Properties that should not be intercepted by the proxy. */
const INTERNAL_PROPS = new Set([
  'then', 'toJSON', 'valueOf', '$$typeof', 'constructor',
  'nodeType', 'tagName',
])

function createPubProxy(getClient: () => ISandboxClient): PubBackend {
  const nsCache = new Map<string, Record<string, ServiceCallable>>()
  const fnCache = new Map<string, ServiceCallable>()

  return new Proxy({} as PubBackend, {
    get(_target, prop) {
      if (typeof prop === 'symbol' || INTERNAL_PROPS.has(prop as string)) return undefined
      const namespace = prop as string

      let nsProxy = nsCache.get(namespace)
      if (nsProxy) return nsProxy

      nsProxy = new Proxy({} as Record<string, ServiceCallable>, {
        get(_t2, prop2) {
          if (typeof prop2 === 'symbol' || INTERNAL_PROPS.has(prop2 as string)) return undefined
          const serviceName = prop2 as string
          const identifier = `${namespace}:${serviceName}`

          let callable = fnCache.get(identifier)
          if (callable) return callable

          const fn = async (inputs: Record<string, unknown> = {}) => {
            const service = await getClient().getService(identifier)
            return service.call(inputs)
          }
          ;(fn as unknown as ServiceCallable).stream = async (
            inputs: Record<string, unknown>,
            on: (value: Record<string, unknown>) => void
          ) => {
            const service = await getClient().getService(identifier)
            if (!service.stream) throw new Error(`Service "${identifier}" does not support streaming`)
            await service.stream(inputs, on)
          }

          callable = fn as unknown as ServiceCallable
          fnCache.set(identifier, callable)
          return callable
        }
      })

      nsCache.set(namespace, nsProxy)
      return nsProxy
    }
  })
}

// ── Hook ─────────────────────────────────────────────────────────────────

/**
 * Returns a type-safe proxy for calling backend services.
 *
 * @example
 * ```tsx
 * const pub = usePub()
 *
 * // Call a service
 * const result = await pub.combat.Attack({ target_id: 'orc_1' })
 *
 * // Stream a service
 * await pub.narrative.Narrate.stream({ event: 'battle' }, (chunk) => {
 *   console.log(chunk.text)
 * })
 * ```
 */
export function usePub(): PubBackend {
  const clientRef = useRef<ISandboxClient | null>(null)

  return useMemo(() => {
    const getClient = () => {
      if (!clientRef.current) {
        clientRef.current = initSandboxClient()
      }
      return clientRef.current
    }
    return createPubProxy(getClient)
  }, [])
}
