services:
  wiki:
    image: m4tsuri/pubwiki:v1.1
    restart: always
    environment: 
      WIKI_SITE_NAME: ${WIKI_SITE_NAME}
      WIKI_META_NAMESPACE: ${WIKI_META_NAMESPACE}
      WIKI_HOST_URL: ${WIKI_HOST_URL}
      WIKI_LANG: "zh-cn"
      WIKI_ADMIN_USER: ${WIKI_ADMIN_USER}
      WIKI_ADMIN_PASSWORD: ${WIKI_ADMIN_PASSWORD}
      WIKI_DB_ADMIN_PASSWORD: ${WIKI_DB_ADMIN_PASSWORD}
      WIKI_DB_ADMIN_USER: ${WIKI_DB_ADMIN_USER}
      WIKI_DB_HOST: wiki-db
      WIKI_DB_USER: ${WIKI_DB_USER}
      WIKI_DB_PASSWORD: ${WIKI_DB_PASSWORD}
      WIKI_DB_NAME: ${WIKI_DB_NAME}
      WIKI_DB_SHARED_DB: ${WIKI_DB_SHARED_DB}
    volumes:
      - wiki-images:/var/www/html/images
    post_start:
      - command: /var/www/html/setup.sh
        user: www-data
    networks: 
      - wikinet
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.rule=Host(`${WIKI_HOST_URL}`)"
      - "traefik.http.routers.wiki.entrypoints=websecure"
      - "traefik.http.services.wiki.loadbalancer.server.port=80"
      - "traefik.http.routers.wiki.service=wiki"
      - "traefik.http.routers.wiki.tls.certresolver=cloudflare"

volumes:
  wiki-images:

networks:
  proxy:
    name: proxy
    extenal: true
  wikinet:
    name: wikinet
    external: true